import { Faction, ICard, ICardAssets, ICards } from "../core/models";
import { cardsIds } from "./cardsIds";
import { heroesIds } from "./heroesIds";

export const cards: ICards = {
  [cardsIds.aragorn]: {
    id: cardsIds.aragorn,
    cost: 5,
    effect: "Reduce your threat to your starting threat level.",
    description: "Sentinel",
    assets: {
      miniaturePath: "assets/cards_small/aragorn_small.png",
      normalPath: "assets/cards_big/aragorn_big.png"
    } as ICardAssets,
    faction: Faction.good,
    linkedTo: [heroesIds.aragorn],
    available: 1,
    limitedTo: 1
  } as ICard,
  "Arwen": {
    id: cardsIds.arwen,
    cost: 3,
    effect: "Discard a card.",
    description: "Noble",
    assets: {
      normalPath: "assets/cards_big/arwen_big.png",
      miniaturePath: "assets/cards_small/arwen_small.png"
    },
    faction: Faction.good,
    linkedTo: [heroesIds.arwen],
    available: 2,
    limitedTo: 10
  },
  "Durin's Bane": {
    id: cardsIds.durinsBane,
    cost: 27,
    effect: "Regenerate. Indestructible.",
    description: "Balrog",
    assets: {
      normalPath: "assets/cards_big/durinsbane_big.png",
      miniaturePath: "assets/cards_small/durinsbane_small.png"
    },
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 1
  },
  "Barliman Butterbur": {
    id: cardsIds.barlimanButterbur,
    cost: 3,
    effect: "Damage may be assigned to Barliman.",
    description: "Hobbit",
    assets: {
      normalPath: "assets/cards_big/barlimanbutterbur_big.png",
      miniaturePath: "assets/cards_small/barlimanbutterbur_small.png"
    },
    faction: Faction.good,
    linkedTo: [],
    available: 3,
    limitedTo: 10
  },

  "Beregond": {
    id: cardsIds.beregond,
    cost: 4,
    effect: "Lower the cost of weapons by 2.",
    description: "Gondor",
    assets: {
      normalPath: "assets/cards_big/beregond_big.png",
      miniaturePath: "assets/cards_small/beregond_small.png",
    },
    faction: Faction.good,
    linkedTo: [],
    available: 1,
    limitedTo: 10
  },
  "Bilbo": {
    id: cardsIds.bilbo,
    cost: 3,
    effect: "The first player gains control of Bilbo.",
    description: "Hobbit",
    assets: {
      normalPath: "assets/cards_big/bilbo_big.png",
      miniaturePath: "assets/cards_small/bilbo_small.png",
    },
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 4,
    limitedTo: 10
  },
  "Bill Ferny": {
    id: cardsIds.billFerny,
    cost: 5,
    effect: "Raise threat by 1 for each non hero.",
    description: "Bree",
    assets: {
      normalPath: "assets/cards_big/billferny_big.png",
      miniaturePath: "assets/cards_small/billferny_small.png",
    },
    faction: Faction.evil,
    linkedTo: [],
    available: 1,
    limitedTo: 10
  },
  "Bill the Pony": {
    id: cardsIds.billThePony,
    cost: 2,
    effect: "Each hobbit gets +1 hit point.",
    description: "Pony",
    assets: {
      normalPath: "assets/cards_big/billpony_big.png",
      miniaturePath: "assets/cards_small/billpony_small.png",
    },
    faction: Faction.good,
    linkedTo: [],
    available: 2,
    limitedTo: 10
  },
  "Boromir": {
    id: cardsIds.boromir,
    cost: 5,
    effect: "Gondor allies get +1 hit point.",
    description: "Warrior",
    assets: {
      normalPath: "assets/cards_big/boromir_big.png",
      miniaturePath: "assets/cards_small/boromir_small.png",
    },
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 3,
    limitedTo: 2
  },
  "Cave-Troll": {
    id: cardsIds.caveTroll,
    cost: 7,
    effect: "You must damage another character you control.",
    description: "Troll",
    assets: {
      normalPath: "assets/cards_big/cavetroll_big.png",
      miniaturePath: "assets/cards_small/cavetroll_small.png",
    },
    faction: Faction.evil,
    linkedTo: [],
    available: 1,
    limitedTo: 1
  },
  "Celeborn": {
    id: cardsIds.celeborn,
    cost: 4,
    effect: "Gets +1 hit point for each Sylvan ally.",
    description: "Silvan",
    assets: {
      normalPath: "assets/cards_big/celeborn_big.png",
      miniaturePath: "assets/cards_small/celeborn_small.png",
    },
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 2
  },
  "Guard of the Citadel": {
    id: cardsIds.guardOfTheCitadel,
    cost: 2,
    effect: "Gets +2 life points.",
    description: "Gondor",
    assets: {
      normalPath: "assets/cards_big/citadelguard_big.png",
      miniaturePath: "assets/cards_small/citadelguard_small.png",
    },
    faction: Faction.good,
    linkedTo: [],
    available: 2,
    limitedTo: 10
  },
  "Crebain": {
    id: cardsIds.crebain,
    cost: 3,
    effect: "Encounter card effects cannot be canceled.",
    description: "Creature",
    assets: {
      normalPath: "assets/cards_big/crebain_big.png",
      miniaturePath: "assets/cards_small/crebain_small.png",
    },
    faction: Faction.evil,
    linkedTo: [],
    available: 1,
    limitedTo: 10
  },
  "Restless Dead": {
    id: cardsIds.restlessDead,
    cost: 2,
    effect: "Return card to the staging area.",
    description: "Undead",
    assets: {
      normalPath: "assets/cards_big/restlessdead_big.png",
      miniaturePath: "assets/cards_small/restlessdead_small.png",
    },
    faction: Faction.evil,
    linkedTo: [],
    available: 1,
    limitedTo: 10
  },
  "Shadow Host Captain": {
    id: cardsIds.shadowHostCaptain,
    cost: 6,
    effect: "Gets +2 hit points and +2 life points.",
    description: "Undead",
    assets: {
      normalPath: "assets/cards_big/shadowhostcaptain_big.png",
      miniaturePath: "assets/cards_small/shadowhostcaptain_small.png",
    },
    faction: Faction.evil,
    linkedTo: [],
    available: 2,
    limitedTo: 2
  },
  "Dead Lord": {
    id: cardsIds.deadLord,
    cost: 3,
    effect: "Put an Undead card in your hand.",
    description: "Undead",
    assets: {
      normalPath: "assets/cards_big/deadlord_big.png",
      miniaturePath: "assets/cards_small/deadlord_small.png",
    },
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 1
  },
  "Denethor": {
    id: cardsIds.denethor,
    cost: 3,
    effect: "Add 2 resources to your pool.",
    description: "Steward",
    assets: {
      normalPath: "assets/cards_big/denethor_big.png",
      miniaturePath: "assets/cards_small/denethor_small.png",
    },
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 2,
    limitedTo: 1
  },
  "Dunhere": {
    id: cardsIds.dunhere,
    cost: 4,
    effect: "Can target enemies in the staging area.",
    description: "Rohan",
    asstes: {
      normalPath: "assets/cards_big/dunhere_big.png",
      miniaturePath: "assets/cards_small/dunhere_small.png",
    },
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 10
  },
  "Eagles": {
    id: cardsIds.eagles,
    cost: 4,
    effect: "Gets +1 hit point for each weapon.",
    description: "Eagle",
    assets: {
      normalPath: "assets/cards_big/eagles_big.png",
      miniaturePath: "assets/cards_small/eagles_small.png",
    },
    faction: Faction.good,
    linkedTo: [],
    available: 1,
    limitedTo: 3
  },
  "Elfhelm": {
    id: cardsIds.elfhelm,
    cost: 4,
    effect: "Each hero gets +1 life point.",
    description: "Scout",
    assets: {
      normalPath: "assets/cards_big/elfhelm_big.png",
      miniaturePath: "assets/cards_small/elfhelm_small.png",
    },
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 10
  },
  "Elladan": {
    id: cardsIds.elladan,
    cost: 4,
    effect: "Pay 1 resource from your pool.",
    description: "Noldor",
    assets: {
      normalPath: "assets/cards_big/elladan_big.png",
      miniaturePath: "assets/cards_small/elladan_small.png",
    },
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 1
  },
  "Elrohir": {
    id: cardsIds.elrohir,
    cost: 4,
    effect: "While Elladan is in play, Elrohir gets +2 hit points.",
    description: "Noldor",
    assets: {
      normalPath: "assets/cards_big/elrohir_big.png",
      miniaturePath: "assets/cards_small/elrohir_small.png",
    },
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 2,
    limitedTo: 1
  },
  "Elrond": {
    id: cardsIds.elrond,
    cost: 4,
    effect: "Spend resources from Elrond's pool for allies.",
    description: "Noldor",
    assets: {
      normalPath: "assets/cards_big/elrond_big.png",
      miniaturePath: "assets/cards_small/elrond_small.png",
    },
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 2,
    limitedTo: 1
  },
  "Eomer": {
    id: cardsIds.eomer,
    cost: 4,
    effect: "If an allie dies, Eomer gets +2 life points.",
    description: "Rohan",
    assets: {
      normalPath: "assets/cards_big/eomer_big.png",
      miniaturePath: "assets/cards_small/eomer_small.png",
    },
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 2,
    limitedTo: 3
  },
  "Eowyn": {
    id: cardsIds.eowyn,
    cost: 3,
    effect: "Discard 1 card from your hand.",
    description: "Rohan",
    assets: {
      normalPath: "assets/cards_big/eowyn_big.png",
      miniaturePath: "assets/cards_small/eowyn_small.png",
    },
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 10
  },
  "Erkenbrand": {
    id: cardsIds.erkenbrand,
    cost: 4,
    effect: "If Erkenbrand is defending he gets +1 hit point.",
    description: "Rohan",
    assets: {
      normalPath: "assets/cards_big/erkenbrand_big.png",
      miniaturePath: "assets/cards_small/erkenbrand_small.png",
    },
    faction: Faction.good,
    linkedTo: [],
    available: 4,
    limitedTo: 10
  },
  "Faramir": {
    id: cardsIds.faramir,
    cost: 5,
    effect: "Ready an ally you control.",
    description: "Ranger",
    assets: {
      normalPath: "assets/cards_big/faramir_big.png",
      miniaturePath: "assets/cards_small/faramir_small.png",
    },
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 10
  },
  "Fell Rider": {
    id: cardsIds.fellRider,
    cost: 6,
    effect: "Cannot have non-Morgul attachments.",
    description: "Nazgul",
    assets: {
      normalPath: "assets/cards_big/fellrider_big.png",
      miniaturePath: "assets/cards_small/fellrider_small.png",
    },
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 10
  },
  "Frodo": {
    id: cardsIds.frodo,
    cost: 2,
    effect: "Exhaust the One Ring and spend 1 resource.",
    description: "Hobbit",
    assets: {
      normalPath: "assets/cards_big/frodo_big.png",
      miniaturePath: "assets/cards_small/frodo_small.png",
    },
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 2,
    limitedTo: 10
  },
  "Galadriel": {
    id: cardsIds.galadriel,
    cost: 4,
    effect: "Galadriel cannot attack or defend.",
    description: "Noldor",
    assets: {
      normalPath: "assets/cards_big/galadriel_big.png",
      miniaturePath: "assets/cards_small/galadriel_small.png",
    },
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 2
  },
  "Gandalf": {
    id: cardsIds.gandalf,
    cost: 5,
    effect: "Play with the top card of your deck face up.",
    description: "Istari",
    assets: {
      normalPath: "assets/cards_big/gandalf_big.png",
      miniaturePath: "assets/cards_small/gandalf_small.png",
    },
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 1
  },
  "Gimli": {
    id: cardsIds.gimli,
    cost: 5,
    effect: "Gets +1 hit points for each damage he takes.",
    description: "Dwarf",
    assets: {
      normalPath: "assets/cards_big/gimli_big.png",
      miniaturePath: "assets/cards_small/gimli_small.png",
    },
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 2,
    limitedTo: 10
  },
  "Glorfindel": {
    id: cardsIds.Glorfindel",
    cost: 5,
    effect: "Raise threat by 1.",
    description: "Noldor",
    normalPath: "assets/cards_big/glorfindel_big.png",
    miniaturePath: "assets/cards_small/glorfindel_small.png",
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 2,
    limitedTo: 2},
  "Gollum": {
    id: cardsIds.Gollum",
    cost: 5,
    effect: "Gollum attacks Bilbo Baggins.",
    description: "Gollum",
    normalPath: "assets/cards_big/gollum_big.png",
    miniaturePath: "assets/cards_small/gollum_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 3,
    limitedTo: 1},
  "Grima": {
    id: cardsIds.Grima",
    cost: 3,
    effect: "Lower the cost of the next card you play by 1.",
    description: "Isengard",
    normalPath: "assets/cards_big/grima_big.png",
    miniaturePath: "assets/cards_small/grima_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 2,
    limitedTo: 10},
  "Grishnakh": {
    id: cardsIds.Grishnakh",
    cost: 5,
    effect: "Place a Captive underneath Isengard.",
    description: "Orc",
    normalPath: "assets/cards_big/grishnakh_big.png",
    miniaturePath: "assets/cards_small/grishnakh_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 3},
  "Haldir": {
    id: cardsIds.Haldir",
    cost: 3,
    effect: "Resolves attacks against an ennemy not engaged.",
    description: "Ranger",
    normalPath: "assets/cards_big/haldir_big.png",
    miniaturePath: "assets/cards_small/haldir_small.png",
    faction: Faction.good,
    linkedTo: [],
    available: 2,
    limitedTo: 10},
  "Hama": {
    id: cardsIds.Hama",
    cost: 4,
    effect: "Return an event from your discard pile.",
    description: "Rohan",
    normalPath: "assets/cards_big/hama_big.png",
    miniaturePath: "assets/cards_small/hama_small.png",
    faction: Faction.good,
    linkedTo: [],
    available: 1,
    limitedTo: 10},
  "Captain of Harad": {
    id: cardsIds.Captain of Harad",
    cost: 5,
    effect: "Each Harad enemy gets +1 hit points.",
    description: "Harad",
    normalPath: "assets/cards_big/haradcaptain_big.png",
    miniaturePath: "assets/cards_small/haradcaptain_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 10},
  "Haradrim Elite": {
    id: cardsIds.Haradrim Elite",
    cost: 3,
    effect: "Makes an immediate attck from the staging area.",
    description: "Harad",
    normalPath: "assets/cards_big/haradrimelite_big.png",
    miniaturePath: "assets/cards_small/haradrimelite_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 3,
    limitedTo: 10},
  "Haradrim Soldier": {
    id: cardsIds.Haradrim Soldier",
    cost: 4,
    effect: "Makes an immadiate attack after engaging you.",
    description: "Harad",
    normalPath: "assets/cards_big/haradrimsoldier_big.png",
    miniaturePath: "assets/cards_small/haradrimsoldier_small.png",
    faction: Faction.evil,
    linkedTo: [],
    available: 3,
    limitedTo: 3},
  "Hill Troll": {
    id: cardsIds.Hill Troll",
    cost: 9,
    effect: "Excess damage must be assigned as an increase of threat.",
    description: "Troll",
    normalPath: "assets/cards_big/hilltroll_big.png",
    miniaturePath: "assets/cards_small/hilltroll_small.png",
    faction: Faction.evil,
    linkedTo: [],
    available: 1,
    limitedTo: 1},
  "Imarahil": {
    id: cardsIds.Imrahil",
    cost: 4,
    effect: "After a character dies, Imrahil gets ready.",
    description: "Gondor",
    normalPath: "assets/cards_big/imrahil_big.png",
    miniaturePath: "assets/cards_small/imrahil_small.png",
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 10},
  "Lieutenant of Orthanc": {
    id: cardsIds.Lieutenant of Orthanc",
    cost: 5,
    effect: "Enemy discards a card if a character dies.",
    description: "Isengard",
    normalPath: "assets/cards_big/orthanclieutenant_big.png",
    miniaturePath: "assets/cards_small/orthanclieutenant_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 2,
    limitedTo: 10},
  "Isengard Orc": {
    id: cardsIds.Isengard Orc",
    cost: 3,
    effect: "Discard a random card or reveal an encounter card.",
    description: "Orc",
    normalPath: "assets/cards_big/isengardorc_big.png",
    miniaturePath: "assets/cards_small/isengardorc_small.png",
    faction: Faction.evil,
    linkedTo: [],
    available: 4,
    limitedTo: 10},
  "Soldier of Isengard": {
    id: cardsIds.Soldier of Isengard",
    cost: 4,
    effect: "Toughness. Archery. Place 1 progress on current quest.",
    description: "Uruk-hai",
    normalPath: "assets/cards_big/isengardsoldier_big.png",
    miniaturePath: "assets/cards_small/isengardsoldier_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 10},
  "Isengard Uruk": {
    id: cardsIds.Isengard Uruk",
    cost: 4,
    effect: "Archery. Assign 3 damage among characters you control.",
    description: "Uruk-hai",
    normalPath: "assets/cards_big/isengarduruk_big.png",
    miniaturePath: "assets/cards_small/isengarduruk_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 2,
    limitedTo: 3},
  "Knights of the Swan": {
    id: cardsIds.Knights of the Swan",
    cost: 1,
    effect: "Each Outlands character gets +1 hit points.",
    description: "Outlands",
    normalPath: "assets/cards_big/swanknignts_big.png",
    miniaturePath: "assets/cards_small/swanknights_small.png",
    faction: Faction.good,
    linkedTo: [],
    available: 2,
    limitedTo: 10},
  "Landroval": {
    id: cardsIds.Landroval",
    cost: 4,
    effect: "Landroval cannot have restricted attachments.",
    description: "Eagle",
    normalPath: "assets/cards_big/landroval_big.png",
    miniaturePath: "assets/cards_small/landroval_small.png",
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 2},
  "Legolas": {
    id: cardsIds.Legolas",
    cost: 4,
    effect: "Ranged. Place 2 progress tokens on the current quest.",
    description: "Sylvan",
    normalPath: "assets/cards_big/legolas_big.png",
    miniaturePath: "assets/cards_small/legolas_small.png",
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 1},
  "Mablung": {
    id: cardsIds.Mablung",
    cost: 4,
    effect: "Add 1 resource to Mablung's resource pool.",
    description: "Ranger",
    normalPath: "assets/cards_big/mablung_big.png",
    miniaturePath: "assets/cards_small/mablung_small.png",
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 10},
  "Farmer Maggot": {
    id: cardsIds.Farmer Maggot",
    cost: 2,
    effect: "Deal 1 damage to an enemy engaged with you.",
    description: "Hobbit",
    normalPath: "assets/cards_big/maggot_big.png",
    miniaturePath: "assets/cards_small/maggot_small.png",
    faction: Faction.good,
    linkedTo: [],
    available: 2,
    limitedTo: 10},
  "Merry": {
    id: cardsIds.Merry",
    cost: 2,
    effect: "Exhaust Merry to reduce your threat.",
    description: "Hobbit",
    normalPath: "assets/cards_big/merry_big.png",
    miniaturePath: "assets/cards_small/merry_small.png",
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 3,
    limitedTo: 10},
  "Lieutenant of Mordor": {
    id: cardsIds.Lieutenant of Mordor",
    cost: 5,
    effect: "Allies cannot defend against Lieutenant of Mordor.",
    description: "Mordor",
    normalPath: "assets/cards_big/mordorlieutenant_big.png",
    miniaturePath: "assets/cards_small/mordorlieutenant_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 2},
  "Morgul Orc": {
    id: cardsIds.Morgul Orc",
    cost: 3,
    effect: "Discard 1 random card from your hand.",
    description: "Orc",
    normalPath: "assets/cards_big/morgulorc_big.png",
    miniaturePath: "assets/cards_small/morgulorc_small.png",
    faction: Faction.evil,
    linkedTo: [],
    available: 2,
    limitedTo: 3},
  "Mumak": {
    id: cardsIds.Mumak",
    cost: 12,
    effect: "No attachments can be attached to Mumak.",
    description: "Harad",
    normalPath: "assets/cards_big/mumak_big.png",
    miniaturePath: "assets/cards_small/mumak_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 1},
  "Nazgul of Dol Guldur": {
    id: cardsIds.Nazgul of Dol Guldur",
    cost: 9,
    effect: "Move Nazgul of Dol Guldur into the staging area.",
    description: "Nazgul",
    normalPath: "assets/cards_big/nazguldolguldur_big.png",
    miniaturePath: "assets/cards_small/nazguldolguldur_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 2,
    limitedTo: 2},
  "Orc Ambusher": {
    id: cardsIds.Orc Ambusher",
    cost: 3,
    effect: "Discard 1 non-objective ally you control.",
    description: "Orc",
    normalPath: "assets/cards_big/orcambusher_big.png",
    miniaturePath: "assets/cards_small/orcambusher_small.png",
    faction: Faction.evil,
    linkedTo: [],
    available: 3,
    limitedTo: 10},
  "Orc Raiders": {
    id: cardsIds.Orc Raiders",
    cost: 3,
    effect: "Player discards 2 attachments he controls.",
    description: "Nazgul",
    normalPath: "assets/cards_big/orcraiders_big.png",
    miniaturePath: "assets/cards_small/orcraiders_small.png",
    faction: Faction.evil,
    linkedTo: [],
    available: 1,
    limitedTo: 10},
  "Pippin": {
    id: cardsIds.Pippin",
    cost: 2,
    effect: "Raise your threat by 3 and returns it to the staging area.",
    description: "Hobbit",
    normalPath: "assets/cards_big/pippin_big.png",
    miniaturePath: "assets/cards_small/pippin_small.png",
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 10},
  "Radagast": {
    id: cardsIds.Radagast",
    cost: 3,
    effect: "Collects 1 resource each resource phase.",
    description: "Istari",
    normalPath: "assets/cards_big/radagast_big.png",
    miniaturePath: "assets/cards_small/radagast_small.png",
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 2},
  "Rider of the Mark": {
    id: cardsIds.Rider of the Mark",
    cost: 2,
    effect: "Give control of Rider of the Mark to another player.",
    description: "Rohan",
    normalPath: "assets/cards_big/riderofthemark_big.png",
    miniaturePath: "assets/cards_small/riderofthemark_small.png",
    faction: Faction.good,
    linkedTo: [],
    available: 2,
    limitedTo: 10},
  "Ringwraith": {
    id: cardsIds.Ringwraith",
    cost: 5,
    effect: "Deals an additionnal damage.",
    description: "Nazgul",
    normalPath: "assets/cards_big/ringwraith_big.png",
    miniaturePath: "assets/cards_small/ringwraith_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 2,
    limitedTo: 9},
  "Saruman": {
    id: cardsIds.Saruman",
    cost: 6,
    effect: "Indestructible. Immune to player card effects.",
    description: "Istari",
    normalPath: "assets/cards_big/saruman_big.png",
    miniaturePath: "assets/cards_small/saruman_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 1},
  "Southron Commander": {
    id: cardsIds.Southron Commander",
    cost: 6,
    effect: "Southron Commander makes an immediate attack.",
    description: "Harad",
    normalPath: "assets/cards_big/southroncommander_big.png",
    miniaturePath: "assets/cards_small/southroncommander_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 2},
  "Southron Company": {
    id: cardsIds.Southron Company",
    cost: 5,
    effect: "Gets +2 life points and +2 hit points.",
    description: "Harad",
    normalPath: "assets/cards_big/southroncompany_big.png",
    miniaturePath: "assets/cards_small/southroncompany_small.png",
    faction: Faction.evil,
    linkedTo: [],
    available: 1,
    limitedTo: 10},
  "Southron Mercenary": {
    id: cardsIds.Southron Mercenary",
    cost: 4,
    effect: "Archery X. X is the number of players.",
    description: "Harad",
    normalPath: "assets/cards_big/southronmercenary_big.png",
    miniaturePath: "assets/cards_small/southronmercenary_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 2,
    limitedTo: 4},
  "Theoden": {
    id: cardsIds.Theoden",
    cost: 4,
    effect: "Each hero gets +1 hit point.",
    description: "Rohan",
    normalPath: "assets/cards_big/theoden_big.png",
    miniaturePath: "assets/cards_small/theoden_small.png",
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 2},
  "Theodred": {
    id: cardsIds.Theodred",
    cost: 4,
    effect: "Add 1 resource to a hero pool.",
    description: "Rohan",
    normalPath: "assets/cards_big/theodred_big.png",
    miniaturePath: "assets/cards_small/theodred_small.png",
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 3},
  "Treebeard": {
    id: cardsIds.Treebeard",
    cost: 5,
    effect: "Cannot have restricted attachments.",
    description: "Ent",
    normalPath: "assets/cards_big/treebeard_big.png",
    miniaturePath: "assets/cards_small/treebeard_small.png",
    faction: Faction.good,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 2},
  "Ugluk": {
    id: cardsIds.Ugluk",
    cost: 6,
    effect: "Toughness 3. Cannot have attachments.",
    description: "Uruk-hai",
    normalPath: "assets/cards_big/ugluk_big.png",
    miniaturePath: "assets/cards_small/ugluk_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 1},
  "Ugluk's Uruk-Hai": {
    id: cardsIds.Ugluk's Uruk-Hai",
    cost: 5,
    effect: "Peril. Toughness 1. Archery 1.",
    description: "Uruk-hai",
    normalPath: "assets/cards_big/ugluksurukhai_big.png",
    miniaturePath: "assets/cards_small/ugluksurukhai_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 2,
    limitedTo: 3},
  "Umbar Assassin": {
    id: cardsIds.Umbar Assassin",
    cost: 5,
    effect: "Archery 2. Player must deal 3 damage to a hero.",
    description: "Brigand",
    normalPath: "assets/cards_big/umbarassassin_big.png",
    miniaturePath: "assets/cards_small/umbarassassin_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 10},
  "Umbar Captain": {
    id: cardsIds.Umbar Captain",
    cost: 5,
    effect: "Characters you control cannot attack Ship ennemies.",
    description: "Corsair",
    normalPath: "assets/cards_big/umbarcaptain_big.png",
    miniaturePath: "assets/cards_small/umbarcaptain_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 2},
  "Umbar Raider": {
    id: cardsIds.Umbar Raider",
    cost: 4,
    effect: "Gets +1 hit points for each resource on it.",
    description: "Corsair",
    normalPath: "assets/cards_big/umbarraider_big.png",
    miniaturePath: "assets/cards_small/umbarraider_small.png",
    faction: Faction.evil,
    linkedTo: [],
    available: 1,
    limitedTo: 2},
  "Uruk Soldier": {
    id: cardsIds.Uruk Soldier",
    cost: 2,
    effect: "Destroys a character.",
    description: "Uruk-hai",
    normalPath: "assets/cards_big/uruksoldier_big.png",
    miniaturePath: "assets/cards_small/uruksoldier_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 2,
    limitedTo: 2},
  "Uruk-Hai Fighter": {
    id: cardsIds.Uruk-Hai Fighter",
    cost: 3,
    effect: "Toughness 2. Returns it to the staging area.",
    description: "Uruk-hai",
    normalPath: "assets/cards_big/urukhaifighter_big.png",
    miniaturePath: "assets/cards_small/urukhaifighter_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 3,
    limitedTo: 10},
  "Uruk Lieutenant": {
    id: cardsIds.Uruk Lieutenant",
    cost: 3,
    effect: "Add an Orc ennemy to the staging area.",
    description: "Uruk",
    normalPath: "assets/cards_big/uruklieutenant_big.png",
    miniaturePath: "assets/cards_small/uruklieutenant_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 2,
    limitedTo: 10},
  "Wargs": {
    id: cardsIds.Wargs",
    cost: 3,
    effect: "Return Wargs to the staging area after it attacks.",
    description: "Creature",
    normalPath: "assets/cards_big/wargs_big.png",
    miniaturePath: "assets/cards_small/wargs_small.png",
    faction: Faction.evil,
    linkedTo: [],
    available: 3,
    limitedTo: 10},
  "Witch-King": {
    id: cardsIds.Witch-King",
    cost: 11,
    effect: "Player cannot play attachments on the Witch-King.",
    description: "Nazgul",
    normalPath: "assets/cards_big/witchking_big.png",
    miniaturePath: "assets/cards_small/witchking_small.png",
    faction: Faction.evil,
    linkedTo: ["Hero X", "Hero Y"],
    available: 1,
    limitedTo: 1}
};

