import { Faction, ICard, ICardAssets, ICards } from "../core/models";
import { cardsIds } from "./cardsIds";
import { heroesIds } from "./heroesIds";

export const cards: ICards = {
  [cardsIds.aragorn]: {
    assets: {
      miniaturePath: 'assets/cards_small/aragorn_small.png',
      normalPath: 'assets/cards_big/aragorn_big.png'
    } as ICardAssets,
    available: 1,
    cost: 5,
    description: 'Sentinel',
    effect: 'Reduce your threat to your starting threat level.',
    faction: Faction.good,
    limitedTo: 1,
    linkedTo: heroesIds.aragorn
  } as ICard
}

// cards = {
//   "Arwen": {
//     "name": "Arwen",
//     "cost": 3,
//     "effect": "Discard a card.",
//     "description": "Noble",
//     "big_path": r"assets\cards_big\arwen_big.png",
//     "small_path": r"assets\cards_small\arwen_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 2,
//     "limited_to": 10},
//   "Durin's Bane": {
//     "name": "Durin's Bane",
//     "cost": 27,
//     "effect": "Regenerate. Indestructible.",
//     "description": "Balrog",
//     "big_path": r"assets\cards_big\durinsbane_big.png",
//     "small_path": r"assets\cards_small\durinsbane_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 1},
//   "Barliman Butterbur": {
//     "name": "Barliman Butterbur",
//     "cost": 3,
//     "effect": "Damage may be assigned to Barliman.",
//     "description": "Hobbit",
//     "big_path": r"assets\cards_big\barlimanbutterbur_big.png",
//     "small_path": r"assets\cards_small\barlimanbutterbur_small.png",
//     "faction": "Good",
//     "linked_to": [],
//     "available": 3,
//     "limited_to": 10},
//   "Beregond": {
//     "name": "Beregond",
//     "cost": 4,
//     "effect": "Lower the cost of weapons by 2.",
//     "description": "Gondor",
//     "big_path": r"assets\cards_big\beregond_big.png",
//     "small_path": r"assets\cards_small\beregond_small.png",
//     "faction": "Good",
//     "linked_to": [],
//     "available": 1,
//     "limited_to": 10},
//   "Bilbo": {
//     "name": "Bilbo",
//     "cost": 3,
//     "effect": "The first player gains control of Bilbo.",
//     "description": "Hobbit",
//     "big_path": r"assets\cards_big\bilbo_big.png",
//     "small_path": r"assets\cards_small\bilbo_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 4,
//     "limited_to": 10},
//   "Bill Ferny": {
//     "name": "Bill Ferny",
//     "cost": 5,
//     "effect": "Raise threat by 1 for each non hero.",
//     "description": "Bree",
//     "big_path": r"assets\cards_big\billferny_big.png",
//     "small_path": r"assets\cards_small\billferny_small.png",
//     "faction": "Evil",
//     "linked_to": [],
//     "available": 1,
//     "limited_to": 10},
//   "Bill the Pony": {
//     "name": "Bill the Pony",
//     "cost": 2,
//     "effect": "Each hobbit gets +1 hit point.",
//     "description": "Pony",
//     "big_path": r"assets\cards_big\billpony_big.png",
//     "small_path": r"assets\cards_small\billpony_small.png",
//     "faction": "Good",
//     "linked_to": [],
//     "available": 2,
//     "limited_to": 10},
//   "Boromir": {
//     "name": "Boromir",
//     "cost": 5,
//     "effect": "Gondor allies get +1 hit point.",
//     "description": "Warrior",
//     "big_path": r"assets\cards_big\boromir_big.png",
//     "small_path": r"assets\cards_small\boromir_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 3,
//     "limited_to": 2},
//   "Cave-Troll": {
//     "name": "Cave-Troll",
//     "cost": 7,
//     "effect": "You must damage another character you control.",
//     "description": "Troll",
//     "big_path": r"assets\cards_big\cavetroll_big.png",
//     "small_path": r"assets\cards_small\cavetroll_small.png",
//     "faction": "Evil",
//     "linked_to": [],
//     "available": 1,
//     "limited_to": 1},
//   "Celeborn": {
//     "name": "Celeborn",
//     "cost": 4,
//     "effect": "Gets +1 hit point for each Sylvan ally.",
//     "description": "Silvan",
//     "big_path": r"assets\cards_big\celeborn_big.png",
//     "small_path": r"assets\cards_small\celeborn_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 2},
//   "Guard of the Citadel": {
//     "name": "Guard of the Citadel",
//     "cost": 2,
//     "effect": "Gets +2 life points.",
//     "description": "Gondor",
//     "big_path": r"assets\cards_big\citadelguard_big.png",
//     "small_path": r"assets\cards_small\citadelguard_small.png",
//     "faction": "Good",
//     "linked_to": [],
//     "available": 2,
//     "limited_to": 10},
//   "Crebain": {
//     "name": "Crebain",
//     "cost": 3,
//     "effect": "Encounter card effects cannot be canceled.",
//     "description": "Creature",
//     "big_path": r"assets\cards_big\crebain_big.png",
//     "small_path": r"assets\cards_small\crebain_small.png",
//     "faction": "Evil",
//     "linked_to": [],
//     "available": 1,
//     "limited_to": 10},
//   "Restless Dead": {
//     "name": "Restless Dead",
//     "cost": 2,
//     "effect": "Return card to the staging area.",
//     "description": "Undead",
//     "big_path": r"assets\cards_big\restlessdead_big.png",
//     "small_path": r"assets\cards_small\restlessdead_small.png",
//     "faction": "Evil",
//     "linked_to": [],
//     "available": 1,
//     "limited_to": 10},
//   "Shadow Host Captain": {
//     "name": "Shadow Host Captain",
//     "cost": 6,
//     "effect": "Gets +2 hit points and +2 life points.",
//     "description": "Undead",
//     "big_path": r"assets\cards_big\shadowhostcaptain_big.png",
//     "small_path": r"assets\cards_small\shadowhostcaptain_small.png",
//     "faction": "Evil",
//     "linked_to": [],
//     "available": 2,
//     "limited_to": 2},
//   "Dead Lord": {
//     "name": "Dead Lord",
//     "cost": 3,
//     "effect": "Put an Undead card in your hand.",
//     "description": "Undead",
//     "big_path": r"assets\cards_big\deadlord_big.png",
//     "small_path": r"assets\cards_small\deadlord_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 1},
//   "Denethor": {
//     "name": "Denethor",
//     "cost": 3,
//     "effect": "Add 2 resources to your pool.",
//     "description": "Steward",
//     "big_path": r"assets\cards_big\denethor_big.png",
//     "small_path": r"assets\cards_small\denethor_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 2,
//     "limited_to": 1},
//   "Dunhere": {
//     "name": "Dunhere",
//     "cost": 4,
//     "effect": "Can target enemies in the staging area.",
//     "description": "Rohan",
//     "big_path": r"assets\cards_big\dunhere_big.png",
//     "small_path": r"assets\cards_small\dunhere_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 10},
//   "Eagles": {
//     "name": "Eagles",
//     "cost": 4,
//     "effect": "Gets +1 hit point for each weapon.",
//     "description": "Eagle",
//     "big_path": r"assets\cards_big\eagles_big.png",
//     "small_path": r"assets\cards_small\eagles_small.png",
//     "faction": "Good",
//     "linked_to": [],
//     "available": 1,
//     "limited_to": 3},
//   "Elfhelm": {
//     "name": "Elfhelm",
//     "cost": 4,
//     "effect": "Each hero gets +1 life point.",
//     "description": "Scout",
//     "big_path": r"assets\cards_big\elfhelm_big.png",
//     "small_path": r"assets\cards_small\elfhelm_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 10},
//   "Elladan": {
//     "name": "Elladan",
//     "cost": 4,
//     "effect": "Pay 1 resource from your pool.",
//     "description": "Noldor",
//     "big_path": r"assets\cards_big\elladan_big.png",
//     "small_path": r"assets\cards_small\elladan_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 1},
//   "Elrohir": {
//     "name": "Elrohir",
//     "cost": 4,
//     "effect": "While Elladan is in play, Elrohir gets +2 hit points.",
//     "description": "Noldor",
//     "big_path": r"assets\cards_big\elrohir_big.png",
//     "small_path": r"assets\cards_small\elrohir_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 2,
//     "limited_to": 1},
//   "Elrond": {
//     "name": "Elrond",
//     "cost": 4,
//     "effect": "Spend resources from Elrond's pool for allies.",
//     "description": "Noldor",
//     "big_path": r"assets\cards_big\elrond_big.png",
//     "small_path": r"assets\cards_small\elrond_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 2,
//     "limited_to": 1},
//   "Eomer": {
//     "name": "Eomer",
//     "cost": 4,
//     "effect": "If an allie dies, Eomer gets +2 life points.",
//     "description": "Rohan",
//     "big_path": r"assets\cards_big\eomer_big.png",
//     "small_path": r"assets\cards_small\eomer_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 2,
//     "limited_to": 3},
//   "Eowyn": {
//     "name": "Eowyn",
//     "cost": 3,
//     "effect": "Discard 1 card from your hand.",
//     "description": "Rohan",
//     "big_path": r"assets\cards_big\eowyn_big.png",
//     "small_path": r"assets\cards_small\eowyn_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 10},
//   "Erkenbrand": {
//     "name": "Erkenbrand",
//     "cost": 4,
//     "effect": "If Erkenbrand is defending he gets +1 hit point.",
//     "description": "Rohan",
//     "big_path": r"assets\cards_big\erkenbrand_big.png",
//     "small_path": r"assets\cards_small\erkenbrand_small.png",
//     "faction": "Good",
//     "linked_to": [],
//     "available": 4,
//     "limited_to": 10},
//   "Faramir": {
//     "name": "Faramir",
//     "cost": 5,
//     "effect": "Ready an ally you control.",
//     "description": "Ranger",
//     "big_path": r"assets\cards_big\faramir_big.png",
//     "small_path": r"assets\cards_small\faramir_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 10},
//   "Fell Rider": {
//     "name": "Fell Rider",
//     "cost": 6,
//     "effect": "Cannot have non-Morgul attachments.",
//     "description": "Nazgul",
//     "big_path": r"assets\cards_big\fellrider_big.png",
//     "small_path": r"assets\cards_small\fellrider_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 10},
//   "Frodo": {
//     "name": "Frodo",
//     "cost": 2,
//     "effect": "Exhaust the One Ring and spend 1 resource.",
//     "description": "Hobbit",
//     "big_path": r"assets\cards_big\frodo_big.png",
//     "small_path": r"assets\cards_small\frodo_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 2,
//     "limited_to": 10},
//   "Galadriel": {
//     "name": "Galadriel",
//     "cost": 4,
//     "effect": "Galadriel cannot attack or defend.",
//     "description": "Noldor",
//     "big_path": r"assets\cards_big\galadriel_big.png",
//     "small_path": r"assets\cards_small\galadriel_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 2},
//   "Gandalf": {
//     "name": "Gandalf",
//     "cost": 5,
//     "effect": "Play with the top card of your deck face up.",
//     "description": "Istari",
//     "big_path": r"assets\cards_big\gandalf_big.png",
//     "small_path": r"assets\cards_small\gandalf_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 1},
//   "Gimli": {
//     "name": "Gimli",
//     "cost": 5,
//     "effect": "Gets +1 hit points for each damage he takes.",
//     "description": "Dwarf",
//     "big_path": r"assets\cards_big\gimli_big.png",
//     "small_path": r"assets\cards_small\gimli_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 2,
//     "limited_to": 10},
//   "Glorfindel": {
//     "name": "Glorfindel",
//     "cost": 5,
//     "effect": "Raise threat by 1.",
//     "description": "Noldor",
//     "big_path": r"assets\cards_big\glorfindel_big.png",
//     "small_path": r"assets\cards_small\glorfindel_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 2,
//     "limited_to": 2},
//   "Gollum": {
//     "name": "Gollum",
//     "cost": 5,
//     "effect": "Gollum attacks Bilbo Baggins.",
//     "description": "Gollum",
//     "big_path": r"assets\cards_big\gollum_big.png",
//     "small_path": r"assets\cards_small\gollum_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 3,
//     "limited_to": 1},
//   "Grima": {
//     "name": "Grima",
//     "cost": 3,
//     "effect": "Lower the cost of the next card you play by 1.",
//     "description": "Isengard",
//     "big_path": r"assets\cards_big\grima_big.png",
//     "small_path": r"assets\cards_small\grima_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 2,
//     "limited_to": 10},
//   "Grishnakh": {
//     "name": "Grishnakh",
//     "cost": 5,
//     "effect": "Place a Captive underneath Isengard.",
//     "description": "Orc",
//     "big_path": r"assets\cards_big\grishnakh_big.png",
//     "small_path": r"assets\cards_small\grishnakh_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 3},
//   "Haldir": {
//     "name": "Haldir",
//     "cost": 3,
//     "effect": "Resolves attacks against an ennemy not engaged.",
//     "description": "Ranger",
//     "big_path": r"assets\cards_big\haldir_big.png",
//     "small_path": r"assets\cards_small\haldir_small.png",
//     "faction": "Good",
//     "linked_to": [],
//     "available": 2,
//     "limited_to": 10},
//   "Hama": {
//     "name": "Hama",
//     "cost": 4,
//     "effect": "Return an event from your discard pile.",
//     "description": "Rohan",
//     "big_path": r"assets\cards_big\hama_big.png",
//     "small_path": r"assets\cards_small\hama_small.png",
//     "faction": "Good",
//     "linked_to": [],
//     "available": 1,
//     "limited_to": 10},
//   "Captain of Harad": {
//     "name": "Captain of Harad",
//     "cost": 5,
//     "effect": "Each Harad enemy gets +1 hit points.",
//     "description": "Harad",
//     "big_path": r"assets\cards_big\haradcaptain_big.png",
//     "small_path": r"assets\cards_small\haradcaptain_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 10},
//   "Haradrim Elite": {
//     "name": "Haradrim Elite",
//     "cost": 3,
//     "effect": "Makes an immediate attck from the staging area.",
//     "description": "Harad",
//     "big_path": r"assets\cards_big\haradrimelite_big.png",
//     "small_path": r"assets\cards_small\haradrimelite_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 3,
//     "limited_to": 10},
//   "Haradrim Soldier": {
//     "name": "Haradrim Soldier",
//     "cost": 4,
//     "effect": "Makes an immadiate attack after engaging you.",
//     "description": "Harad",
//     "big_path": r"assets\cards_big\haradrimsoldier_big.png",
//     "small_path": r"assets\cards_small\haradrimsoldier_small.png",
//     "faction": "Evil",
//     "linked_to": [],
//     "available": 3,
//     "limited_to": 3},
//   "Hill Troll": {
//     "name": "Hill Troll",
//     "cost": 9,
//     "effect": "Excess damage must be assigned as an increase of threat.",
//     "description": "Troll",
//     "big_path": r"assets\cards_big\hilltroll_big.png",
//     "small_path": r"assets\cards_small\hilltroll_small.png",
//     "faction": "Evil",
//     "linked_to": [],
//     "available": 1,
//     "limited_to": 1},
//   "Imarahil": {
//     "name": "Imrahil",
//     "cost": 4,
//     "effect": "After a character dies, Imrahil gets ready.",
//     "description": "Gondor",
//     "big_path": r"assets\cards_big\imrahil_big.png",
//     "small_path": r"assets\cards_small\imrahil_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 10},
//   "Lieutenant of Orthanc": {
//     "name": "Lieutenant of Orthanc",
//     "cost": 5,
//     "effect": "Enemy discards a card if a character dies.",
//     "description": "Isengard",
//     "big_path": r"assets\cards_big\orthanclieutenant_big.png",
//     "small_path": r"assets\cards_small\orthanclieutenant_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 2,
//     "limited_to": 10},
//   "Isengard Orc": {
//     "name": "Isengard Orc",
//     "cost": 3,
//     "effect": "Discard a random card or reveal an encounter card.",
//     "description": "Orc",
//     "big_path": r"assets\cards_big\isengardorc_big.png",
//     "small_path": r"assets\cards_small\isengardorc_small.png",
//     "faction": "Evil",
//     "linked_to": [],
//     "available": 4,
//     "limited_to": 10},
//   "Soldier of Isengard": {
//     "name": "Soldier of Isengard",
//     "cost": 4,
//     "effect": "Toughness. Archery. Place 1 progress on current quest.",
//     "description": "Uruk-hai",
//     "big_path": r"assets\cards_big\isengardsoldier_big.png",
//     "small_path": r"assets\cards_small\isengardsoldier_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 10},
//   "Isengard Uruk": {
//     "name": "Isengard Uruk",
//     "cost": 4,
//     "effect": "Archery. Assign 3 damage among characters you control.",
//     "description": "Uruk-hai",
//     "big_path": r"assets\cards_big\isengarduruk_big.png",
//     "small_path": r"assets\cards_small\isengarduruk_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 2,
//     "limited_to": 3},
//   "Knights of the Swan": {
//     "name": "Knights of the Swan",
//     "cost": 1,
//     "effect": "Each Outlands character gets +1 hit points.",
//     "description": "Outlands",
//     "big_path": r"assets\cards_big\swanknignts_big.png",
//     "small_path": r"assets\cards_small\swanknights_small.png",
//     "faction": "Good",
//     "linked_to": [],
//     "available": 2,
//     "limited_to": 10},
//   "Landroval": {
//     "name": "Landroval",
//     "cost": 4,
//     "effect": "Landroval cannot have restricted attachments.",
//     "description": "Eagle",
//     "big_path": r"assets\cards_big\landroval_big.png",
//     "small_path": r"assets\cards_small\landroval_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 2},
//   "Legolas": {
//     "name": "Legolas",
//     "cost": 4,
//     "effect": "Ranged. Place 2 progress tokens on the current quest.",
//     "description": "Sylvan",
//     "big_path": r"assets\cards_big\legolas_big.png",
//     "small_path": r"assets\cards_small\legolas_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 1},
//   "Mablung": {
//     "name": "Mablung",
//     "cost": 4,
//     "effect": "Add 1 resource to Mablung's resource pool.",
//     "description": "Ranger",
//     "big_path": r"assets\cards_big\mablung_big.png",
//     "small_path": r"assets\cards_small\mablung_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 10},
//   "Farmer Maggot": {
//     "name": "Farmer Maggot",
//     "cost": 2,
//     "effect": "Deal 1 damage to an enemy engaged with you.",
//     "description": "Hobbit",
//     "big_path": r"assets\cards_big\maggot_big.png",
//     "small_path": r"assets\cards_small\maggot_small.png",
//     "faction": "Good",
//     "linked_to": [],
//     "available": 2,
//     "limited_to": 10},
//   "Merry": {
//     "name": "Merry",
//     "cost": 2,
//     "effect": "Exhaust Merry to reduce your threat.",
//     "description": "Hobbit",
//     "big_path": r"assets\cards_big\merry_big.png",
//     "small_path": r"assets\cards_small\merry_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 3,
//     "limited_to": 10},
//   "Lieutenant of Mordor": {
//     "name": "Lieutenant of Mordor",
//     "cost": 5,
//     "effect": "Allies cannot defend against Lieutenant of Mordor.",
//     "description": "Mordor",
//     "big_path": r"assets\cards_big\mordorlieutenant_big.png",
//     "small_path": r"assets\cards_small\mordorlieutenant_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 2},
//   "Morgul Orc": {
//     "name": "Morgul Orc",
//     "cost": 3,
//     "effect": "Discard 1 random card from your hand.",
//     "description": "Orc",
//     "big_path": r"assets\cards_big\morgulorc_big.png",
//     "small_path": r"assets\cards_small\morgulorc_small.png",
//     "faction": "Evil",
//     "linked_to": [],
//     "available": 2,
//     "limited_to": 3},
//   "Mumak": {
//     "name": "Mumak",
//     "cost": 12,
//     "effect": "No attachments can be attached to Mumak.",
//     "description": "Harad",
//     "big_path": r"assets\cards_big\mumak_big.png",
//     "small_path": r"assets\cards_small\mumak_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 1},
//   "Nazgul of Dol Guldur": {
//     "name": "Nazgul of Dol Guldur",
//     "cost": 9,
//     "effect": "Move Nazgul of Dol Guldur into the staging area.",
//     "description": "Nazgul",
//     "big_path": r"assets\cards_big\nazguldolguldur_big.png",
//     "small_path": r"assets\cards_small\nazguldolguldur_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 2,
//     "limited_to": 2},
//   "Orc Ambusher": {
//     "name": "Orc Ambusher",
//     "cost": 3,
//     "effect": "Discard 1 non-objective ally you control.",
//     "description": "Orc",
//     "big_path": r"assets\cards_big\orcambusher_big.png",
//     "small_path": r"assets\cards_small\orcambusher_small.png",
//     "faction": "Evil",
//     "linked_to": [],
//     "available": 3,
//     "limited_to": 10},
//   "Orc Raiders": {
//     "name": "Orc Raiders",
//     "cost": 3,
//     "effect": "Player discards 2 attachments he controls.",
//     "description": "Nazgul",
//     "big_path": r"assets\cards_big\orcraiders_big.png",
//     "small_path": r"assets\cards_small\orcraiders_small.png",
//     "faction": "Evil",
//     "linked_to": [],
//     "available": 1,
//     "limited_to": 10},
//   "Pippin": {
//     "name": "Pippin",
//     "cost": 2,
//     "effect": "Raise your threat by 3 and returns it to the staging area.",
//     "description": "Hobbit",
//     "big_path": r"assets\cards_big\pippin_big.png",
//     "small_path": r"assets\cards_small\pippin_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 10},
//   "Radagast": {
//     "name": "Radagast",
//     "cost": 3,
//     "effect": "Collects 1 resource each resource phase.",
//     "description": "Istari",
//     "big_path": r"assets\cards_big\radagast_big.png",
//     "small_path": r"assets\cards_small\radagast_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 2},
//   "Rider of the Mark": {
//     "name": "Rider of the Mark",
//     "cost": 2,
//     "effect": "Give control of Rider of the Mark to another player.",
//     "description": "Rohan",
//     "big_path": r"assets\cards_big\riderofthemark_big.png",
//     "small_path": r"assets\cards_small\riderofthemark_small.png",
//     "faction": "Good",
//     "linked_to": [],
//     "available": 2,
//     "limited_to": 10},
//   "Ringwraith": {
//     "name": "Ringwraith",
//     "cost": 5,
//     "effect": "Deals an additionnal damage.",
//     "description": "Nazgul",
//     "big_path": r"assets\cards_big\ringwraith_big.png",
//     "small_path": r"assets\cards_small\ringwraith_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 2,
//     "limited_to": 9},
//   "Saruman": {
//     "name": "Saruman",
//     "cost": 6,
//     "effect": "Indestructible. Immune to player card effects.",
//     "description": "Istari",
//     "big_path": r"assets\cards_big\saruman_big.png",
//     "small_path": r"assets\cards_small\saruman_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 1},
//   "Southron Commander": {
//     "name": "Southron Commander",
//     "cost": 6,
//     "effect": "Southron Commander makes an immediate attack.",
//     "description": "Harad",
//     "big_path": r"assets\cards_big\southroncommander_big.png",
//     "small_path": r"assets\cards_small\southroncommander_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 2},
//   "Southron Company": {
//     "name": "Southron Company",
//     "cost": 5,
//     "effect": "Gets +2 life points and +2 hit points.",
//     "description": "Harad",
//     "big_path": r"assets\cards_big\southroncompany_big.png",
//     "small_path": r"assets\cards_small\southroncompany_small.png",
//     "faction": "Evil",
//     "linked_to": [],
//     "available": 1,
//     "limited_to": 10},
//   "Southron Mercenary": {
//     "name": "Southron Mercenary",
//     "cost": 4,
//     "effect": "Archery X. X is the number of players.",
//     "description": "Harad",
//     "big_path": r"assets\cards_big\southronmercenary_big.png",
//     "small_path": r"assets\cards_small\southronmercenary_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 2,
//     "limited_to": 4},
//   "Theoden": {
//     "name": "Theoden",
//     "cost": 4,
//     "effect": "Each hero gets +1 hit point.",
//     "description": "Rohan",
//     "big_path": r"assets\cards_big\theoden_big.png",
//     "small_path": r"assets\cards_small\theoden_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 2},
//   "Theodred": {
//     "name": "Theodred",
//     "cost": 4,
//     "effect": "Add 1 resource to a hero pool.",
//     "description": "Rohan",
//     "big_path": r"assets\cards_big\theodred_big.png",
//     "small_path": r"assets\cards_small\theodred_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 3},
//   "Treebeard": {
//     "name": "Treebeard",
//     "cost": 5,
//     "effect": "Cannot have restricted attachments.",
//     "description": "Ent",
//     "big_path": r"assets\cards_big\treebeard_big.png",
//     "small_path": r"assets\cards_small\treebeard_small.png",
//     "faction": "Good",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 2},
//   "Ugluk": {
//     "name": "Ugluk",
//     "cost": 6,
//     "effect": "Toughness 3. Cannot have attachments.",
//     "description": "Uruk-hai",
//     "big_path": r"assets\cards_big\ugluk_big.png",
//     "small_path": r"assets\cards_small\ugluk_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 1},
//   "Ugluk's Uruk-Hai": {
//     "name": "Ugluk's Uruk-Hai",
//     "cost": 5,
//     "effect": "Peril. Toughness 1. Archery 1.",
//     "description": "Uruk-hai",
//     "big_path": r"assets\cards_big\ugluksurukhai_big.png",
//     "small_path": r"assets\cards_small\ugluksurukhai_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 2,
//     "limited_to": 3},
//   "Umbar Assassin": {
//     "name": "Umbar Assassin",
//     "cost": 5,
//     "effect": "Archery 2. Player must deal 3 damage to a hero.",
//     "description": "Brigand",
//     "big_path": r"assets\cards_big\umbarassassin_big.png",
//     "small_path": r"assets\cards_small\umbarassassin_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 10},
//   "Umbar Captain": {
//     "name": "Umbar Captain",
//     "cost": 5,
//     "effect": "Characters you control cannot attack Ship ennemies.",
//     "description": "Corsair",
//     "big_path": r"assets\cards_big\umbarcaptain_big.png",
//     "small_path": r"assets\cards_small\umbarcaptain_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 2},
//   "Umbar Raider": {
//     "name": "Umbar Raider",
//     "cost": 4,
//     "effect": "Gets +1 hit points for each resource on it.",
//     "description": "Corsair",
//     "big_path": r"assets\cards_big\umbarraider_big.png",
//     "small_path": r"assets\cards_small\umbarraider_small.png",
//     "faction": "Evil",
//     "linked_to": [],
//     "available": 1,
//     "limited_to": 2},
//   "Uruk Soldier": {
//     "name": "Uruk Soldier",
//     "cost": 2,
//     "effect": "Destroys a character.",
//     "description": "Uruk-hai",
//     "big_path": r"assets\cards_big\uruksoldier_big.png",
//     "small_path": r"assets\cards_small\uruksoldier_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 2,
//     "limited_to": 2},
//   "Uruk-Hai Fighter": {
//     "name": "Uruk-Hai Fighter",
//     "cost": 3,
//     "effect": "Toughness 2. Returns it to the staging area.",
//     "description": "Uruk-hai",
//     "big_path": r"assets\cards_big\urukhaifighter_big.png",
//     "small_path": r"assets\cards_small\urukhaifighter_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 3,
//     "limited_to": 10},
//   "Uruk Lieutenant": {
//     "name": "Uruk Lieutenant",
//     "cost": 3,
//     "effect": "Add an Orc ennemy to the staging area.",
//     "description": "Uruk",
//     "big_path": r"assets\cards_big\uruklieutenant_big.png",
//     "small_path": r"assets\cards_small\uruklieutenant_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 2,
//     "limited_to": 10},
//   "Wargs": {
//     "name": "Wargs",
//     "cost": 3,
//     "effect": "Return Wargs to the staging area after it attacks.",
//     "description": "Creature",
//     "big_path": r"assets\cards_big\wargs_big.png",
//     "small_path": r"assets\cards_small\wargs_small.png",
//     "faction": "Evil",
//     "linked_to": [],
//     "available": 3,
//     "limited_to": 10},
//   "Witch-King": {
//     "name": "Witch-King",
//     "cost": 11,
//     "effect": "Player cannot play attachments on the Witch-King.",
//     "description": "Nazgul",
//     "big_path": r"assets\cards_big\witchking_big.png",
//     "small_path": r"assets\cards_small\witchking_small.png",
//     "faction": "Evil",
//     "linked_to": ["Hero X", "Hero Y"],
//     "available": 1,
//     "limited_to": 1}
// }
