import { HeroSize, IHero, IHeroAssets, IHeroCharacteristics, IHeroes } from "../core/models";
import { heroesIds } from "./heroesIds";

export const heroes: IHeroes = {
  [heroesIds.aragorn]: {
    id: heroesIds.aragorn,
    characteristics: {
      speed: 7,
      initiative: 10,
      lifePoints: 10,
      magicPoints: 0,
      armor: 7,
      range: 8,
      size: HeroSize.medium,
      agility: 7,
      stamina: 8,
      strength: 7,
      magic: 0,
      mental: 7,
      attack: 8,
      rangedAttack: 6,
      attackArmor: 2
    } as IHeroCharacteristics,
    cost: 100,
    unique: true,
    skills: [
      "Anduril",
      "For Frodo"
    ],
    description: "Aragorn II, son of Arathorn was a Ranger of the North, first introduced with the name Strider at Bree.",
    assets: {
      tokenPath: "assets/heroesTokens/aragorn.png",
      tokenInitPath: "assets/heroesTokensInit/aragorn.png",
      miniaturePath: "assets/heroesMiniatures/aragorn.png",
      battlefieldPath: "assets/heroesBattlefield/aragorn.png"
    } as IHeroAssets
  } as IHero,
  [heroesIds.arwen]: {
    id: heroesIds.arwen,
    characteristics: {
      speed: 7,
      initiative: 7,
      lifePoints: 7,
      magicPoints: 8,
      armor: 5,
      range: 0,
      size: HeroSize.medium,
      agility: 8,
      stamina: 6,
      strength: 5,
      magic: 8,
      mental: 8,
      attack: 5,
      rangedAttack: 0,
      attackArmor: 1
    } as IHeroCharacteristics,
    cost: 75,
    unique: true,
    skills: [
      "Hadhafang",
      "Athelas"
    ],
    description: "Arwen was the Half-Elven daughter of Elrond and Celebrían.",
    assets: {
      tokenPath: "assets/heroesTokens/arwen.png",
      tokenInitPath: "assets/heroesTokensInit/arwen.png",
      miniaturePath: "assets/heroesMiniatures/arwen.png",
      battlefieldPath: "assets/heroesBattlefield/arwen.png"
    } as IHeroAssets
  } as IHero,
  [heroesIds.balrog]: {
    id: heroesIds.balrog,
    characteristics: {
      speed: 5,
      initiative: 5,
      lifePoints: 30,
      magicPoints: 10,
      armor: 10,
      range: 0,
      size: HeroSize.large,
      agility: 4,
      stamina: 10,
      strength: 10,
      magic: 8,
      mental: 7,
      attack: 12,
      rangedAttack: 10,
      attackArmor: 4
    } as IHeroCharacteristics,
    cost: 200,
    unique: false,
    skills: [
      "Fire whip",
      "Fire blade"
    ],
    description: "The Balrogs were Maiar corrupted by Morgoth during the creation of Arda, who cloaked themselves in shadow and flame.",
    assets: {
      tokenPath: "assets/heroesTokens/balrog.png",
      miniaturePath: "assets/heroesMiniatures/balrog.png",
      tokenInitPath: "assets/heroesTokensInit/balrog.png",
      battlefieldPath: "assets/heroesBattlefield/balrog.png"
    } as IHeroAssets
  } as IHero,
  [heroesIds.barrowWight]: {
    id: heroesIds.barrowWight,
    characteristics: {
      speed: 3,
      initiative: 3,
      lifePoints: 6,
      magicPoints: 7,
      armor: 3,
      range: 0,
      size: HeroSize.medium,
      agility: 3,
      stamina: 4,
      strength: 5,
      magic: 8,
      mental: 8,
      attack: 5,
      rangedAttack: 0,
      attackArmor: 1
    } as IHeroCharacteristics,
    cost: 40,
    unique: false,
    skills: [
      "Dead hand",
      "Sleep trap"
    ],
    description: "The Barrow-wights were a kind of undead-like creatures, dead bones animated by evil spirits.",
    assets: {
      tokenPath: "assets/heroesTokens/barrow_wight.png",
      miniaturePath: "assets/heroesMiniatures/barrow_wight.png",
      tokenInitPath: "assets/heroesTokensInit/barrow_wight.png",
      battlefieldPath: "assets/heroesBattlefield/barrow_wight.png"
    } as IHeroAssets
  } as IHero
};


JSON.stringify({
  characteristics: {
    speed: v.speed,
    initiative: v.initiative,
    lifePoints: v.life_points,
    magicPoints: v.magic_points,
    armor: v.armor,
    range: v.range,
    size: v.size,
    agility: v.agility,
    stamina: v.stamina,
    strength: v.strength,
    magic: v.magic,
    mental: v.mental,
    attack: v.attack,
    rangedAttack: v.ranged_attack,
    attackArmor: v.attack_armor
  },
  cost: v.cost,
  unique: v.unique,
  skills: v.skills,
  description: v.description,
  assets: {
    tokenPath: v.token_path.replace("heroes_tokens", "heroesTokens"),
    miniaturePath: v.miniature_path.replace("heroes_miniatures", "heroesMiniatures"),
    tokenInitPath: v.token_init_path.replace("heroes_tokens_init", "heroesTokensInit"),
    battlefieldPath: v.battlefield_path.replace("heroes_battlefield", "heroesBattlefield")
  }
});

//   "Imrahil": {
//     "speed": 5,
//     "initiative": 5,
//     "life_points": 7,
//     "magic_points": 0,
//     "armor": 7,
//     "range": 0,
//     "size": "M",
//     "agility": 5,
//     "stamina": 7,
//     "strength": 7,
//     "magic": 0,
//     "mental": 5,
//     "attack": 7,
//     "ranged_attack": 0,
//     "attack_armor": 2,
//     "cost": 75,
//     "unique": true,
//     "skills": ["Desperate Charge", "Prince Imrahil"],
//     "description": "Imrahil, also known as Prince Imrahil, was the twenty-second Prince of Dol Amroth.",
//     "token_path": "assets/heroes_tokens/imrahil.png",
//     "token_init_path": "assets/heroes_tokens_init/imrahil.png",
//     "miniature_path": "assets/heroes_miniatures/imrahil.png",
//     "battlefield_path": "assets/heroes_battlefield/imrahil.png"},
//   "Gandalf": {
//     "speed": 8,
//     "initiative": 8,
//     "life_points": 15,
//     "magic_points": 15,
//     "armor": 5,
//     "range": 0,
//     "size": "M",
//     "agility": 5,
//     "stamina": 8,
//     "strength": 7,
//     "magic": 15,
//     "mental": 12,
//     "attack": 8,
//     "ranged_attack": 0,
//     "attack_armor": 2,
//     "cost": 160,
//     "unique": true,
//     "skills": ["You shall not pass", "Shock Wave"],
//     "description": "Gandalf was one of the five Istari sent to Middle-earth by the Valar in the Third Age. In Valinor he was known as Olórin.",
//     "token_path": "assets/heroes_tokens/gandalf.png",
//     "token_init_path": "assets/heroes_tokens_init/gandalf.png",
//     "miniature_path": "assets/heroes_miniatures/gandalf.png",
//     "battlefield_path": "assets/heroes_battlefield/gandalf.png"},
//   "Radagast": {
//     "speed": 8,
//     "initiative": 7,
//     "life_points": 10,
//     "magic_points": 11,
//     "armor": 5,
//     "range": 0,
//     "size": "M",
//     "agility": 5,
//     "stamina": 7,
//     "strength": 6,
//     "magic": 14,
//     "mental": 12,
//     "attack": 7,
//     "ranged_attack": 0,
//     "attack_armor": 2,
//     "cost": 130,
//     "unique": true,
//     "skills": ["Powers of the Maiar", "Animals friend"],
//     "description": "Radagast was one of the five Wizards, or Istari. He was a good friend of Gandalf the Grey, whom he aided occasionally.",
//     "token_path": "assets/heroes_tokens/radagast.png",
//     "token_init_path": "assets/heroes_tokens_init/radagast.png",
//     "miniature_path": "assets/heroes_miniatures/radagast.png",
//     "battlefield_path": "assets/heroes_battlefield/radagast.png"},
//   "Legolas": {
//     "speed": 9,
//     "initiative": 9,
//     "life_points": 7,
//     "magic_points": 0,
//     "armor": 6,
//     "range": 10,
//     "size": "M",
//     "agility": 9,
//     "stamina": 8,
//     "strength": 5,
//     "magic": 0,
//     "mental": 6,
//     "attack": 8,
//     "ranged_attack": 9,
//     "attack_armor": 2,
//     "cost": 120,
//     "unique": true,
//     "skills": ["Double Arrow", "Mortal knife dance"],
//     "description": "Legolas was an elf of the Woodland Realm of Mirkwood. He was of Sindarin heritage, being the only recorded son of King Thranduil.",
//     "token_path": "assets/heroes_tokens/legolas.png",
//     "token_init_path": "assets/heroes_tokens_init/legolas.png",
//     "miniature_path": "assets/heroes_miniatures/legolas.png",
//     "battlefield_path": "assets/heroes_battlefield/legolas.png"},
//   "Glorfindel": {
//     "speed": 11,
//     "initiative": 11,
//     "life_points": 12,
//     "magic_points": 0,
//     "armor": 8,
//     "range": 10,
//     "size": "M",
//     "agility": 10,
//     "stamina": 8,
//     "strength": 6,
//     "magic": 0,
//     "mental": 6,
//     "attack": 8,
//     "ranged_attack": 8,
//     "attack_armor": 2,
//     "cost": 150,
//     "unique": true,
//     "skills": ["Balrog killer", "Firstborn"],
//     "description": "Glorfindel was one of the mighty of the Firstborn, and the Lord of the House of the Golden Flower in Gondolin.",
//     "token_path": "assets/heroes_tokens/glorfindel.png",
//     "token_init_path": "assets/heroes_tokens_init/glorfindel.png",
//     "miniature_path": "assets/heroes_miniatures/glorfindel.png",
//     "battlefield_path": "assets/heroes_battlefield/glorfindel.png"},
//   "Gil-galad": {
//     "speed": 12,
//     "initiative": 12,
//     "life_points": 16,
//     "magic_points": 10,
//     "armor": 8,
//     "range": 2,
//     "size": "M",
//     "agility": 12,
//     "stamina": 8,
//     "strength": 8,
//     "magic": 8,
//     "mental": 7,
//     "attack": 10,
//     "ranged_attack": 10,
//     "attack_armor": 3,
//     "cost": 200,
//     "unique": true,
//     "skills": ["Aeglos", "Narya and Vilya"],
//     "description": "Gil-galad was a Ñoldorin Elf, last High King of the Ñoldor in Middle-earth and bore many titles.",
//     "token_path": "assets/heroes_tokens/gil-galad.png",
//     "token_init_path": "assets/heroes_tokens_init/gil-galad.png",
//     "miniature_path": "assets/heroes_miniatures/gil-galad.png",
//     "battlefield_path": "assets/heroes_battlefield/gil-galad.png"},
//   "Frodo": {
//     "speed": 4,
//     "initiative": 4,
//     "life_points": 5,
//     "magic_points": 0,
//     "armor": 7,
//     "range": 5,
//     "size": "S",
//     "agility": 8,
//     "stamina": 5,
//     "strength": 4,
//     "magic": 0,
//     "mental": 7,
//     "attack": 5,
//     "ranged_attack": 3,
//     "attack_armor": 1,
//     "cost": 40,
//     "unique": true,
//     "skills": ["Light of Earendil", "Invisibility"],
//     "description": "Frodo Baggins was a hobbit of the Third Age, the most famous of all Hobbits in the histories for his leading role in the Quest of the Ring.",
//     "token_path": "assets/heroes_tokens/frodo.png",
//     "token_init_path": "assets/heroes_tokens_init/frodo.png",
//     "miniature_path": "assets/heroes_miniatures/frodo.png",
//     "battlefield_path": "assets/heroes_battlefield/frodo.png"},
//   "Bilbo": {
//     "speed": 4,
//     "initiative": 4,
//     "life_points": 6,
//     "magic_points": 0,
//     "armor": 5,
//     "range": 7,
//     "size": "S",
//     "agility": 5,
//     "stamina": 5,
//     "strength": 4,
//     "magic": 0,
//     "mental": 7,
//     "attack": 3,
//     "ranged_attack": 3,
//     "attack_armor": 1,
//     "cost": 35,
//     "unique": true,
//     "skills": ["Elves friend", "Dwarves friend"],
//     "description": "Bilbo was the first Hobbit to become famous in the world at large and one of the few to visit the The Undying Lands.",
//     "token_path": "assets/heroes_tokens/bilbo.png",
//     "token_init_path": "assets/heroes_tokens_init/bilbo.png",
//     "miniature_path": "assets/heroes_miniatures/bilbo.png",
//     "battlefield_path": "assets/heroes_battlefield/bilbo.png"},
//   "Samwise": {
//     "speed": 4,
//     "initiative": 4,
//     "life_points": 5,
//     "magic_points": 0,
//     "armor": 3,
//     "range": 5,
//     "size": "S",
//     "agility": 7,
//     "stamina": 5,
//     "strength": 6,
//     "magic": 0,
//     "mental": 8,
//     "attack": 5,
//     "ranged_attack": 3,
//     "attack_armor": 1,
//     "cost": 40,
//     "unique": true,
//     "skills": ["But I can carry you", "Great courage"],
//     "description": "Samwise was Frodo servant and the only member of the fellowship to remain with him till the very end of the journey to Mount Doom.",
//     "token_path": "assets/heroes_tokens/samwise.png",
//     "token_init_path": "assets/heroes_tokens_init/samwise.png",
//     "miniature_path":  "assets/heroes_miniatures/samwise.png",
//     "battlefield_path": "assets/heroes_battlefield/samwise.png"},
//   "Meriadoc": {
//     "speed": 4,
//     "initiative": 6,
//     "life_points": 5,
//     "magic_points": 0,
//     "armor": 3,
//     "range": 6,
//     "size": "S",
//     "agility": 6,
//     "stamina": 5,
//     "strength": 5,
//     "magic": 0,
//     "mental": 6,
//     "attack": 6,
//     "ranged_attack": 3,
//     "attack_armor": 1,
//     "cost": 35,
//     "unique": true,
//     "skills": ["Rock Throwing", "Esquire of Rohan"],
//     "description": "Meriadoc Brandybuck, called The Magnificent, was a Hobbit, the son of Saradoc Brandybuck. Merry was the heir of the Brandybucks to Brandy Hall.",
//     "token_path": "assets/heroes_tokens/meriadoc.png",
//     "token_init_path": "assets/heroes_tokens_init/meriadoc.png",
//     "miniature_path":  "assets/heroes_miniatures/meriadoc.png",
//     "battlefield_path": "assets/heroes_battlefield/meriadoc.png"},
//   "Peregrin": {
//     "speed": 4,
//     "initiative": 6,
//     "life_points": 5,
//     "magic_points": 0,
//     "armor": 3,
//     "range": 6,
//     "size": "S",
//     "agility": 6,
//     "stamina": 5,
//     "strength": 5,
//     "magic": 0,
//     "mental": 6,
//     "attack": 6,
//     "ranged_attack": 3,
//     "attack_armor": 1,
//     "cost": 35,
//     "unique": true,
//     "skills": ["Rock Throwing", "Guardian of the Citadel"],
//     "description": "Peregrin Took was one of the Hobbits in the Fellowship of the Ring. He was the youngest of the Company.",
//     "token_path": "assets/heroes_tokens/peregrin.png",
//     "token_init_path": "assets/heroes_tokens_init/peregrin.png",
//     "miniature_path":  "assets/heroes_miniatures/peregrin.png",
//     "battlefield_path": "assets/heroes_battlefield/peregrin.png"},
//   "Gimli": {
//     "speed": 3,
//     "initiative": 4,
//     "life_points": 20,
//     "magic_points": 0,
//     "armor": 15,
//     "range": 3,
//     "size": "S",
//     "agility": 2,
//     "stamina": 9,
//     "strength": 8,
//     "magic": 0,
//     "mental": 4,
//     "attack": 8,
//     "ranged_attack": 6,
//     "attack_armor": 2,
//     "cost": 90,
//     "unique": true,
//     "skills": ["Wall of steel", "Not the beard"],
//     "description": "Gimli was a dwarf of Durin's Folk, a direct descendant of Durin the Deathless.",
//     "token_path": "assets/heroes_tokens/gimli.png",
//     "token_init_path": "assets/heroes_tokens_init/gimli.png",
//     "miniature_path":  "assets/heroes_miniatures/gimli.png",
//     "battlefield_path": "assets/heroes_battlefield/gimli.png"},
//   "Gloin": {
//     "speed": 3,
//     "initiative": 4,
//     "life_points": 18,
//     "magic_points": 0,
//     "armor": 13,
//     "range": 0,
//     "size": "S",
//     "agility": 2,
//     "stamina": 8,
//     "strength": 8,
//     "magic": 0,
//     "mental": 4,
//     "attack": 7,
//     "ranged_attack": 0,
//     "attack_armor": 2,
//     "cost": 80,
//     "unique": true,
//     "skills": ["", ""],
//     "description": "Glóin was one of the dwarves of Thorin II Oakenshield's company and was the father of Gimli",
//     "token_path": "assets/heroes_tokens/gloin.png",
//     "token_init_path": "assets/heroes_tokens_init/gloin.png",
//     "miniature_path": "assets/heroes_miniatures/gloin.png",
//     "battlefield_path": "assets/heroes_battlefield/gloin.png"},
//   "Boromir": {
//     "speed": 6,
//     "initiative": 6,
//     "life_points": 12,
//     "magic_points": 0,
//     "armor": 9,
//     "range": 0,
//     "size": "M",
//     "agility": 6,
//     "stamina": 9,
//     "strength": 8,
//     "magic": 0,
//     "mental": 6,
//     "attack": 8,
//     "ranged_attack": 0,
//     "attack_armor": 2,
//     "cost": 95,
//     "unique": true,
//     "skills": ["Horn of Gondor", "Sacrifice"],
//     "description": "Boromir was the eldest son of Denethor II, older brother of Faramir.",
//     "token_path": "assets/heroes_tokens/boromir.png",
//     "token_init_path": "assets/heroes_tokens_init/boromir.png",
//     "miniature_path": "assets/heroes_miniatures/boromir.png",
//     "battlefield_path": "assets/heroes_battlefield/boromir.png"},
//   "Denethor": {
//     "speed": 5,
//     "initiative": 5,
//     "life_points": 8,
//     "magic_points": 0,
//     "armor": 8,
//     "range": 0,
//     "size": "M",
//     "agility": 6,
//     "stamina": 7,
//     "strength": 6,
//     "magic": 0,
//     "mental": 5,
//     "attack": 7,
//     "ranged_attack": 0,
//     "attack_armor": 2,
//     "cost": 80,
//     "unique": true,
//     "skills": ["Palantir", "Call of Power"],
//     "description": "Denethor II was the twenty-sixth Ruling Steward of Gondor, and father of the War of the Ring heroes Boromir and Faramir.",
//     "token_path": "assets/heroes_tokens/denethor.png",
//     "token_init_path": "assets/heroes_tokens_init/denethor.png",
//     "miniature_path": "assets/heroes_miniatures/denethor.png",
//     "battlefield_path": "assets/heroes_battlefield/denethor.png"},
//   "Beregond": {
//     "speed": 5,
//     "initiative": 6,
//     "life_points": 7,
//     "magic_points": 0,
//     "armor": 6,
//     "range": 0,
//     "size": "M",
//     "agility": 6,
//     "stamina": 7,
//     "strength": 6,
//     "magic": 0,
//     "mental": 5,
//     "attack": 6,
//     "ranged_attack": 0,
//     "attack_armor": 1,
//     "cost": 60,
//     "unique": true,
//     "skills": ["Steward of Gondor", "Sea captain"],
//     "description": "Beregond was the twentieth Ruling Steward of Gondor.",
//     "token_path": "assets/heroes_tokens/beregond.png",
//     "token_init_path": "assets/heroes_tokens_init/beregond.png",
//     "miniature_path": "assets/heroes_miniatures/beregond.png",
//     "battlefield_path": "assets/heroes_battlefield/beregond.png"},
//   "Faramir": {
//     "speed": 7,
//     "initiative": 7,
//     "life_points": 8,
//     "magic_points": 0,
//     "armor": 6,
//     "range": 8,
//     "size": "M",
//     "agility": 7,
//     "stamina": 7,
//     "strength": 7,
//     "magic": 0,
//     "mental": 7,
//     "attack": 7,
//     "ranged_attack": 6,
//     "attack_armor": 2,
//     "cost": 85,
//     "unique": true,
//     "skills": ["Ranger leader", "Righteous"],
//     "description": "Faramir was the last Ruling Steward of Gondor and the first Prince of Ithilien. The second of Denethor's two sons.",
//     "token_path": "assets/heroes_tokens/faramir.png",
//     "token_init_path": "assets/heroes_tokens_init/faramir.png",
//     "miniature_path": "assets/heroes_miniatures/faramir.png",
//     "battlefield_path": "assets/heroes_battlefield/faramir.png"},
//   "Théoden": {
//     "speed": 7,
//     "initiative": 6,
//     "life_points": 8,
//     "magic_points": 0,
//     "armor": 7,
//     "range": 0,
//     "size": "M",
//     "agility": 6,
//     "stamina": 7,
//     "strength": 6,
//     "magic": 0,
//     "mental": 4,
//     "attack": 7,
//     "ranged_attack": 0,
//     "attack_armor": 2,
//     "cost": 60,
//     "unique": true,
//     "skills": ["Death", "Charge"],
//     "description": "Théoden was the seventeenth King of Rohan. He was the last of the Second Line.",
//     "token_path": "assets/heroes_tokens/theoden.png",
//     "token_init_path": "assets/heroes_tokens_init/theoden.png",
//     "miniature_path": "assets/heroes_miniatures/theoden.png",
//     "battlefield_path": "assets/heroes_battlefield/theoden.png"},
//   "Hama": {
//     "speed": 7,
//     "initiative": 6,
//     "life_points": 7,
//     "magic_points": 0,
//     "armor": 6,
//     "range": 0,
//     "size": "M",
//     "agility": 6,
//     "stamina": 7,
//     "strength": 6,
//     "magic": 0,
//     "mental": 5,
//     "attack": 7,
//     "ranged_attack": 0,
//     "attack_armor": 2,
//     "cost": 55,
//     "unique": true,
//     "skills": ["Doorwald", "Captain of the Guard"],
//     "description": "Háma was a Man of Rohan and the doorward of the Meduseld and captain of Théoden's guard.",
//     "token_path": "assets/heroes_tokens/hama.png",
//     "token_init_path": "assets/heroes_tokens_init/hama.png",
//     "miniature_path": "assets/heroes_miniatures/hama.png",
//     "battlefield_path": "assets/heroes_battlefield/hama.png"},
//   "Eowyn": {
//     "speed": 6,
//     "initiative": 7,
//     "life_points": 7,
//     "magic_points": 0,
//     "armor": 6,
//     "range": 0,
//     "size": "M",
//     "agility": 7,
//     "stamina": 6,
//     "strength": 7,
//     "magic": 0,
//     "mental": 6,
//     "attack": 7,
//     "ranged_attack": 0,
//     "attack_armor": 2,
//     "cost": 65,
//     "unique": true,
//     "skills": ["Lady of Rohan", "For my king"],
//     "description": "Éowyn, the Lady of Rohan, was also known as the Lady of the Shield-arm, the White Lady of Rohan, and Lady of Ithilien.",
//     "token_path": "assets/heroes_tokens/eowyn.png",
//     "token_init_path": "assets/heroes_tokens_init/eowyn.png",
//     "miniature_path": "assets/heroes_miniatures/eowyn.png",
//     "battlefield_path": "assets/heroes_battlefield/eowyn.png"},
//   "Elrond": {
//     "speed": 6,
//     "initiative": 6,
//     "life_points": 10,
//     "magic_points": 8,
//     "armor": 5,
//     "range": 0,
//     "size": "M",
//     "agility": 8,
//     "stamina": 7,
//     "strength": 5,
//     "magic": 8,
//     "mental": 8,
//     "attack": 5,
//     "ranged_attack": 0,
//     "attack_armor": 1,
//     "cost": 80,
//     "unique": true,
//     "skills": ["Water horses", "Science of healing"],
//     "description": "Elrond was the Lord of Rivendell and keeper of the great elven ring Vilya.",
//     "token_path": "assets/heroes_tokens/elrond.png",
//     "token_init_path": "assets/heroes_tokens_init/elrond.png",
//     "miniature_path": "assets/heroes_miniatures/elrond.png",
//     "battlefield_path": "assets/heroes_battlefield/elrond.png"},
//   "Haldir": {
//     "speed": 7,
//     "initiative": 7,
//     "life_points": 7,
//     "magic_points": 0,
//     "armor": 6,
//     "range": 8,
//     "size": "M",
//     "agility": 7,
//     "stamina": 6,
//     "strength": 6,
//     "magic": 0,
//     "mental": 6,
//     "attack": 7,
//     "ranged_attack": 7,
//     "attack_armor": 2,
//     "cost": 70,
//     "unique": true,
//     "skills": ["Rapid fire", "Watcher"],
//     "description": "Haldir was an Elf of Lothlórien, probably a Silvan Elf, and a marchwarden who guarded the forest's northern borders.",
//     "token_path": "assets/heroes_tokens/haldir.png",
//     "token_init_path": "assets/heroes_tokens_init/haldir.png",
//     "miniature_path": "assets/heroes_miniatures/haldir.png",
//     "battlefield_path": "assets/heroes_battlefield/haldir.png"},
//   "Elendil": {
//     "speed": 7,
//     "initiative": 7,
//     "life_points": 9,
//     "magic_points": 0,
//     "armor": 7,
//     "range": 0,
//     "size": "M",
//     "agility": 6,
//     "stamina": 7,
//     "strength": 6,
//     "magic": 0,
//     "mental": 6,
//     "attack": 7,
//     "ranged_attack": 0,
//     "attack_armor": 2,
//     "cost": 85,
//     "unique": true,
//     "skills": ["Narsil", "Founder of Gondor"],
//     "description": "Elendil was the father of Isildur and Anárion, and the first High King of Gondor and Arnor and first King of all the Dúnedain.",
//     "token_path": "assets/heroes_tokens/elendil.png",
//     "token_init_path": "assets/heroes_tokens_init/elendil.png",
//     "miniature_path": "assets/heroes_miniatures/elendil.png",
//     "battlefield_path": "assets/heroes_battlefield/elendil.png"},
//   "Isildur": {
//     "speed": 7,
//     "initiative": 7,
//     "life_points": 8,
//     "magic_points": 0,
//     "armor": 7,
//     "range": 0,
//     "size": "M",
//     "agility": 6,
//     "stamina": 7,
//     "strength": 7,
//     "magic": 0,
//     "mental": 4,
//     "attack": 8,
//     "ranged_attack": 0,
//     "attack_armor": 2,
//     "cost": 90,
//     "unique": true,
//     "skills": ["Shards of Narsil", "Corruption of the Ring"],
//     "description": "Isildur was the son of Elendil and the High King of Gondor and Arnor",
//     "token_path": "assets/heroes_tokens/isildur.png",
//     "token_init_path": "assets/heroes_tokens_init/isildur.png",
//     "miniature_path": "assets/heroes_miniatures/isildur.png",
//     "battlefield_path": "assets/heroes_battlefield/isildur.png"},
//   "Lothlorien Elf": {
//     "speed": 7,
//     "initiative": 6,
//     "life_points": 6,
//     "magic_points": 0,
//     "armor": 6,
//     "range": 7,
//     "size": "M",
//     "agility": 7,
//     "stamina": 5,
//     "strength": 5,
//     "magic": 0,
//     "mental": 5,
//     "attack": 6,
//     "ranged_attack": 5,
//     "attack_armor": 1,
//     "cost": 60,
//     "unique": false,
//     "skills": ["Elven bow", "Elven blade"],
//     "description": "Lothlórien was a forest located next to the lower Misty Mountains.",
//     "token_path": "assets/heroes_tokens/lothlorien_elf.png",
//     "token_init_path": "assets/heroes_tokens_init/lothlorien_elf.png",
//     "miniature_path": "assets/heroes_miniatures/lothlorien_elf.png",
//     "battlefield_path": "assets/heroes_battlefield/lothlorien_elf.png"},
//   "Gondorian Ranger": {
//     "speed": 6,
//     "initiative": 6,
//     "life_points": 7,
//     "magic_points": 0,
//     "armor": 6,
//     "range": 6,
//     "size": "M",
//     "agility": 5,
//     "stamina": 5,
//     "strength": 5,
//     "magic": 0,
//     "mental": 4,
//     "attack": 6,
//     "ranged_attack": 6,
//     "attack_armor": 1,
//     "cost": 45,
//     "unique": false,
//     "skills": ["Gondorian bow", "Gondorian blade"],
//     "description": "The Rangers of Ithilien were a military group whose purpose was to defend Ithilien, the gate to Minas Tirith.",
//     "token_path": "assets/heroes_tokens/gondorian_ranger.png",
//     "token_init_path": "assets/heroes_tokens_init/gondorian_ranger.png",
//     "miniature_path": "assets/heroes_miniatures/gondorian_ranger.png",
//     "battlefield_path": "assets/heroes_battlefield/gondorian_ranger.png"},
//   "Gondorian Soldier": {
//     "speed": 5,
//     "initiative": 5,
//     "life_points": 8,
//     "magic_points": 0,
//     "armor": 7,
//     "range": 0,
//     "size": "M",
//     "agility": 5,
//     "stamina": 6,
//     "strength": 6,
//     "magic": 0,
//     "mental": 5,
//     "attack": 6,
//     "ranged_attack": 0,
//     "attack_armor": 1,
//     "cost": 45,
//     "unique": false,
//     "skills": ["Gondorian blade", "Gondorian armor"],
//     "description": "Gondorians were descended from the Númenórean colonists.",
//     "token_path": "assets/heroes_tokens/gondorian_soldier.png",
//     "token_init_path": "assets/heroes_tokens_init/gondorian_soldier.png",
//     "miniature_path": "assets/heroes_miniatures/gondorian_soldier.png",
//     "battlefield_path": "assets/heroes_battlefield/gondorian_soldier.png"},
//   "Guard of the Citadel": {
//     "speed": 5,
//     "initiative": 5,
//     "life_points": 8,
//     "magic_points": 0,
//     "armor": 8,
//     "range": 0,
//     "size": "M",
//     "agility": 5,
//     "stamina": 6,
//     "strength": 6,
//     "magic": 0,
//     "mental": 5,
//     "attack": 7,
//     "ranged_attack": 0,
//     "attack_armor": 2,
//     "cost": 55,
//     "unique": false,
//     "skills": ["Gondorian spear", "Black steel armor"],
//     "description": "The Guards of the Citadel, sometimes referred to as The Tower Guards, were an elite unit of soldiers in Gondor.",
//     "token_path": "assets/heroes_tokens/citadel_guard.png",
//     "token_init_path": "assets/heroes_tokens_init/citadel_guard.png",
//     "miniature_path": "assets/heroes_miniatures/citadel_guard.png",
//     "battlefield_path": "assets/heroes_battlefield/citadel_guard.png"},
//   "Rohirrim Soldier": {
//     "speed": 5,
//     "initiative": 5,
//     "life_points": 8,
//     "magic_points": 0,
//     "armor": 6,
//     "range": 4,
//     "size": "M",
//     "agility": 5,
//     "stamina": 6,
//     "strength": 6,
//     "magic": 0,
//     "mental": 4,
//     "attack": 6,
//     "ranged_attack": 4,
//     "attack_armor": 1,
//     "cost": 40,
//     "unique": false,
//     "skills": ["Rohan spear", "Rohan blade"],
//     "description": "The Rohirrim were a race of people who inhabited the land of Rohan, which was named after their famous Horses.",
//     "token_path": "assets/heroes_tokens/rohirrim_soldier.png",
//     "token_init_path": "assets/heroes_tokens_init/rohirrim_soldier.png",
//     "miniature_path": "assets/heroes_miniatures/rohirrim_soldier.png",
//     "battlefield_path": "assets/heroes_battlefield/rohirrim_soldier.png"},
//   "Eomer": {
//     "speed": 7,
//     "initiative": 6,
//     "life_points": 9,
//     "magic_points": 0,
//     "armor": 7,
//     "range": 0,
//     "size": "M",
//     "agility": 7,
//     "stamina": 7,
//     "strength": 8,
//     "magic": 0,
//     "mental": 6,
//     "attack": 7,
//     "ranged_attack": 0,
//     "attack_armor": 2,
//     "cost": 90,
//     "unique": true,
//     "skills": ["Master of horses", "We ride north"],
//     "description": "Éomer Éadig, of the House of Eorl, was the eighteenth King of Rohan, and first of the Third Line.",
//     "token_path": "assets/heroes_tokens/eomer.png",
//     "token_init_path": "assets/heroes_tokens_init/eomer.png",
//     "miniature_path": "assets/heroes_miniatures/eomer.png",
//     "battlefield_path": "assets/heroes_battlefield/eomer.png"},
//   "Galadriel": {
//     "speed": 6,
//     "initiative": 7,
//     "life_points": 10,
//     "magic_points": 10,
//     "armor": 5,
//     "range": 0,
//     "size": "M",
//     "agility": 7,
//     "stamina": 6,
//     "strength": 6,
//     "magic": 10,
//     "mental": 9,
//     "attack": 5,
//     "ranged_attack": 0,
//     "attack_armor": 1,
//     "cost": 110,
//     "unique": true,
//     "skills": ["Dark queen", "Nenya"],
//     "description": "Galadriel was a Noldo, one of the Calaquendi, and arguably the most famous and powerful elf of the Third Age.",
//     "token_path": "assets/heroes_tokens/galadriel.png",
//     "token_init_path": "assets/heroes_tokens_init/galadriel.png",
//     "miniature_path": "assets/heroes_miniatures/galadriel.png",
//     "battlefield_path": "assets/heroes_battlefield/galadriel.png"},
//   "Celeborn":  {
//     "speed":  6,
//     "initiative": 7,
//     "life_points": 10,
//     "magic_points": 9,
//     "armor": 5,
//     "range": 0,
//     "size": "M",
//     "agility": 7,
//     "stamina": 6,
//     "strength": 6,
//     "magic": 9,
//     "mental": 13,
//     "attack": 5,
//     "ranged_attack": 0,
//     "attack_armor": 1,
//     "cost": 100,
//     "unique": true,
//     "skills": ["Wisest of all", "Lord of the Galadhrim"],
//     "description": "Celeborn was the Lord of Lothlórien. His wife was Galadriel. Celeborn was said to be one of the wisest Elves in Middle-earth.",
//     "token_path": "assets/heroes_tokens/celeborn.png",
//     "token_init_path": "assets/heroes_tokens_init/celeborn.png",
//     "miniature_path": "assets/heroes_miniatures/celeborn.png",
//     "battlefield_path": "assets/heroes_battlefield/celeborn.png"},
//   "Bombadil": {
//     "speed": 6,
//     "initiative": 10,
//     "life_points": 8,
//     "magic_points": 20,
//     "armor": 2,
//     "range": 0,
//     "size": "M",
//     "agility": 3,
//     "stamina": 6,
//     "strength": 3,
//     "magic": 20,
//     "mental": 20,
//     "attack": 1,
//     "ranged_attack": 0,
//     "attack_armor": 1,
//     "cost": 130,
//     "unique": true,
//     "skills": ["Resurrect", "Untouch by evil"],
//     "description": "Tom Bombadil was an enigmatic figure that lived throughout the history of Arda.",
//     "token_path": "assets/heroes_tokens/bombadil.png",
//     "token_init_path": "assets/heroes_tokens_init/bombadil.png",
//     "miniature_path": "assets/heroes_miniatures/bombadil.png",
//     "battlefield_path": "assets/heroes_battlefield/bombadil.png"},
//   "King of the Dead": {
//     "speed": 6,
//     "initiative": 5,
//     "life_points": 10,
//     "magic_points": 0,
//     "armor": 7,
//     "range": 0,
//     "size": "M",
//     "agility": 6,
//     "stamina": 6,
//     "strength": 5,
//     "magic": 0,
//     "mental": 6,
//     "attack": 7,
//     "ranged_attack": 0,
//     "attack_armor": 2,
//     "cost": 60,
//     "unique": true,
//     "skills": ["Oathbreaker", "Swarm"],
//     "description": "The King of the Mountains, or later, the King of the Dead, was the ruler of the Oathbreakers.",
//     "token_path": "assets/heroes_tokens/king_of_the_dead.png",
//     "token_init_path": "assets/heroes_tokens_init/king_of_the_dead.png",
//     "miniature_path": "assets/heroes_miniatures/king_of_the_dead.png",
//     "battlefield_path": "assets/heroes_battlefield/king_of_the_dead.png"},
//   "Soldier of the Dead": {
//     "speed": 5,
//     "initiative": 5,
//     "life_points": 8,
//     "magic_points": 0,
//     "armor": 6,
//     "range": 4,
//     "size": "M",
//     "agility": 5,
//     "stamina": 6,
//     "strength": 6,
//     "magic": 0,
//     "mental": 4,
//     "attack": 6,
//     "ranged_attack": 2,
//     "attack_armor": 1,
//     "cost": 40,
//     "unique": false,
//     "skills": ["Fantomatic blade", "Fantomatic spear"],
//     "description": "The Army of the Dead, also known as the Dead Men of Dunharrow or Oathbreakers, were the ghosts of deceased Men of the White Mountains.",
//     "token_path": "assets/heroes_tokens/soldier_of_the_dead.png",
//     "token_init_path": "assets/heroes_tokens_init/soldier_of_the_dead.png",
//     "miniature_path": "assets/heroes_miniatures/soldier_of_the_dead.png",
//     "battlefield_path": "assets/heroes_battlefield/soldier_of_the_dead.png"},
//   "Cave Troll": {
//     "speed": 4,
//     "initiative": 5,
//     "life_points": 25,
//     "magic_points": 0,
//     "armor": 9,
//     "range": 0,
//     "size": "B",
//     "agility": 4,
//     "stamina": 8,
//     "strength": 10,
//     "magic": 0,
//     "mental": 3,
//     "attack": 10,
//     "ranged_attack": 0,
//     "attack_armor": 3,
//     "cost": 150,
//     "unique": false,
//     "skills": ["Spear", "Hard skin"],
//     "description": "Cave-trolls are a race of trolls found within the caves of the Misty Mountains.",
//     "token_path": "assets/heroes_tokens/cave_troll.png",
//     "token_init_path": "assets/heroes_tokens_init/cave_troll.png",
//     "miniature_path": "assets/heroes_miniatures/cave_troll.png",
//     "battlefield_path": "assets/heroes_battlefield/cave_troll.png"},
//   "Mordor Orc": {
//     "speed": 6,
//     "initiative": 4,
//     "life_points": 4,
//     "magic_points": 0,
//     "armor": 4,
//     "range": 0,
//     "size": "P",
//     "agility": 5,
//     "stamina": 4,
//     "strength": 4,
//     "magic": 0,
//     "mental": 4,
//     "attack": 4,
//     "ranged_attack": 0,
//     "attack_armor": 1,
//     "cost": 30,
//     "unique": false,
//     "skills": ["Mordor blade", "Mordor armor"],
//     "description": "Many Orcs survived in the deep caves, pits, chambers, and tunnels of Melkor's great underground fortresses of Utumno and Angband.",
//     "token_path": "assets/heroes_tokens/mordor_orc.png",
//     "token_init_path": "assets/heroes_tokens_init/mordor_orc.png",
//     "miniature_path": "assets/heroes_miniatures/mordor_orc.png",
//     "battlefield_path": "assets/heroes_battlefield/mordor_orc.png"},
//   "Berserker": {
//     "speed": 6,
//     "initiative": 5,
//     "life_points": 7,
//     "magic_points": 0,
//     "armor": 3,
//     "range": 5,
//     "size": "M",
//     "agility": 5,
//     "stamina": 6,
//     "strength": 6,
//     "magic": 0,
//     "mental": 4,
//     "attack": 8,
//     "ranged_attack": 5,
//     "attack_armor": 2,
//     "cost": 45,
//     "unique": false,
//     "skills": ["Berserker blade", "Blood rage"],
//     "description": "Berserkers of Isengard were of the most powerful Uruk-hai ever to come out of Saruman's pits.",
//     "token_path": "assets/heroes_tokens/berserker.png",
//     "token_init_path": "assets/heroes_tokens_init/berserker.png",
//     "miniature_path": "assets/heroes_miniatures/berserker.png",
//     "battlefield_path": "assets/heroes_battlefield/berserker.png"},
//   "Nazgul": {
//     "speed": 6,
//     "initiative": 7,
//     "life_points": 12,
//     "magic_points": 5,
//     "armor": 5,
//     "range": 0,
//     "size": "M",
//     "agility": 6,
//     "stamina": 7,
//     "strength": 7,
//     "magic": 5,
//     "mental": 6,
//     "attack": 6,
//     "ranged_attack": 0,
//     "attack_armor": 1,
//     "cost": 90,
//     "unique": false,
//     "skills": ["Morgul blade", "Despair"],
//     "description": "The Nazgûl, also known as the Nine Riders or Black Riders (or simply the Nine), were Sauron's most terrible servants in Middle-earth.",
//     "token_path": "assets/heroes_tokens/nazgul.png",
//     "token_init_path": "assets/heroes_tokens_init/nazgul.png",
//     "miniature_path": "assets/heroes_miniatures/nazgul.png",
//     "battlefield_path": "assets/heroes_battlefield/nazgul.png"},
//   "Sauron": {
//     "speed": 7,
//     "initiative": 7,
//     "life_points": 15,
//     "magic_points": 15,
//     "armor": 12,
//     "range": 0,
//     "size": "G",
//     "agility": 7,
//     "stamina": 9,
//     "strength": 9,
//     "magic": 10,
//     "mental": 12,
//     "attack": 9,
//     "ranged_attack": 0,
//     "attack_armor": 2,
//     "cost": 180,
//     "unique": true,
//     "skills": ["One ring to rule them all", "And in the darkness bind them"],
//     "description": "Sauron was the greatest and most trusted servant of Morgoth before and during the First Age.",
//     "token_path": "assets/heroes_tokens/sauron.png",
//     "token_init_path": "assets/heroes_tokens_init/sauron.png",
//     "miniature_path": "assets/heroes_miniatures/sauron.png",
//     "battlefield_path": "assets/heroes_battlefield/sauron.png"},
//   "Lurtz": {
//     "speed": 7,
//     "initiative": 7,
//     "life_points": 8,
//     "magic_points": 0,
//     "armor": 7,
//     "range": 8,
//     "size": "M",
//     "agility": 7,
//     "stamina": 7,
//     "strength": 7,
//     "magic": 0,
//     "mental": 5,
//     "attack": 8,
//     "ranged_attack": 8,
//     "attack_armor": 2,
//     "cost": 95,
//     "unique": true,
//     "skills": ["Isengard bow", "Born in blood"],
//     "description": "Lurtz was the first of Saruman's Uruk-hai to be bred, and led them into battle against the Fellowship of the Ring at Amon Hen.",
//     "token_path": "assets/heroes_tokens/lurtz.png",
//     "token_init_path": "assets/heroes_tokens_init/lurtz.png",
//     "miniature_path": "assets/heroes_miniatures/lurtz.png",
//     "battlefield_path": "assets/heroes_battlefield/lurtz.png"},
//   "Gothmog":  {
//     "speed":  5,
//     "initiative":  5,
//     "life_points":  9,
//     "magic_points": 0,
//     "armor": 8,
//     "range": 0,
//     "size": "M",
//     "agility": 5,
//     "stamina": 7,
//     "strength": 9,
//     "magic": 0,
//     "mental": 5,
//     "attack": 9,
//     "ranged_attack": 0,
//     "attack_armor": 2,
//     "cost": 90,
//     "unique": true,
//     "skills": ["Mace", "Time of the Orc"],
//     "description": "Gothmog was the lieutenant of the Witch-king in the Third Age, from Minas Morgul, notably at the Battle of the Pelennor Fields.",
//     "token_path": "assets/heroes_tokens/gothmog.png",
//     "token_init_path": "assets/heroes_tokens_init/gothmog.png",
//     "miniature_path": "assets/heroes_miniatures/gothmog.png",
//     "battlefield_path": "assets/heroes_battlefield/gothmog.png"},
//   "Gollum": {
//     "speed": 6,
//     "initiative": 6,
//     "life_points": 6,
//     "magic_points": 0,
//     "armor": 3,
//     "range": 0,
//     "size": "P",
//     "agility": 6,
//     "stamina": 4,
//     "strength": 6,
//     "magic": 0,
//     "mental": 4,
//     "attack": 7,
//     "ranged_attack": 0,
//     "attack_armor": 2,
//     "cost": 40,
//     "unique": true,
//     "skills": ["My precious", "Filthy little Hobbitses"],
//     "description": "Gollum, also known as Sméagol, was a creature who bore the One Ring. He lived in the Misty Mountains for most of his life.",
//     "token_path": "assets/heroes_tokens/gollum.png",
//     "token_init_path": "assets/heroes_tokens_init/gollum.png",
//     "miniature_path": "assets/heroes_miniatures/gollum.png",
//     "battlefield_path": "assets/heroes_battlefield/gollum.png"},
//   "Shagrat": {
//     "speed": 6,
//     "initiative": 5,
//     "life_points": 5,
//     "magic_points": 0,
//     "armor": 5,
//     "range": 0,
//     "size": "P",
//     "agility": 5,
//     "stamina": 5,
//     "strength": 5,
//     "magic": 0,
//     "mental": 5,
//     "attack": 5,
//     "ranged_attack": 0,
//     "attack_armor": 1,
//     "cost": 45,
//     "unique": true,
//     "skills": ["Tower captain", "Morgul rats"],
//     "description": "Shagrat was an Uruk commanding the garrison of the Tower of Cirith Ungol during the War of the Ring.",
//     "token_path": "assets/heroes_tokens/shagrat.png",
//     "token_init_path": "assets/heroes_tokens_init/shagrat.png",
//     "miniature_path": "assets/heroes_miniatures/shagrat.png",
//     "battlefield_path": "assets/heroes_battlefield/shagrat.png"},
//   "Mouth of Sauron": {
//     "speed": 5,
//     "initiative": 5,
//     "life_points": 6,
//     "magic_points": 7,
//     "armor": 6,
//     "range": 0,
//     "size": "M",
//     "agility": 4,
//     "stamina": 6,
//     "strength": 6,
//     "magic": 6,
//     "mental": 6,
//     "attack": 5,
//     "ranged_attack": 0,
//     "attack_armor": 1,
//     "cost": 70,
//     "unique": true,
//     "skills": ["My master bid thee welcome", "Blind servant"],
//     "description": "The Mouth of Sauron was the Dark Lord Sauron's servant and representative at the end of the Third Age.",
//     "token_path": "assets/heroes_tokens/mouth_of_sauron.png",
//     "token_init_path": "assets/heroes_tokens_init/mouth_of_sauron.png",
//     "miniature_path": "assets/heroes_miniatures/mouth_of_sauron.png",
//     "battlefield_path": "assets/heroes_battlefield/mouth_of_sauron.png"},
//   "Grishnakh": {
//     "speed": 6,
//     "initiative": 6,
//     "life_points": 5,
//     "magic_points": 0,
//     "armor": 5,
//     "range": 0,
//     "size": "P",
//     "agility": 5,
//     "stamina": 5,
//     "strength": 5,
//     "magic": 0,
//     "mental": 5,
//     "attack": 4,
//     "ranged_attack": 0,
//     "attack_armor": 1,
//     "cost": 45,
//     "unique": true,
//     "skills": ["Long arms", "Back to Lugburz"],
//     "description": "Grishnákh was a captain of Orcs from Mordor.",
//     "token_path": "assets/heroes_tokens/grishnakh.png",
//     "token_init_path": "assets/heroes_tokens_init/grishnakh.png",
//     "miniature_path": "assets/heroes_miniatures/grishnakh.png",
//     "battlefield_path": "assets/heroes_battlefield/grishnakh.png"},
//   "Saruman": {
//     "speed": 6,
//     "initiative": 6,
//     "life_points": 15,
//     "magic_points": 18,
//     "armor": 5,
//     "range": 0,
//     "size": "M",
//     "agility": 5,
//     "stamina": 7,
//     "strength": 7,
//     "magic": 17,
//     "mental": 13,
//     "attack": 7,
//     "ranged_attack": 0,
//     "attack_armor": 2,
//     "cost": 170,
//     "unique": true,
//     "skills": ["Persuasive voice", "Elements control"],
//     "description": "Saruman the White was the first of the order of Wizards (or Istari) who came to Middle-earth as Emissaries of the Valar in the Third Age.",
//     "token_path": "assets/heroes_tokens/saruman.png",
//     "token_init_path": "assets/heroes_tokens_init/saruman.png",
//     "miniature_path": "assets/heroes_miniatures/saruman.png",
//     "battlefield_path": "assets/heroes_battlefield/saruman.png"},
//   "Grima": {
//     "speed": 3,
//     "initiative": 4,
//     "life_points": 5,
//     "magic_points": 0,
//     "armor": 2,
//     "range": 0,
//     "size": "M",
//     "agility": 4,
//     "stamina": 4,
//     "strength": 3,
//     "magic": 0,
//     "mental": 4,
//     "attack": 4,
//     "ranged_attack": 0,
//     "attack_armor": 1,
//     "cost": 25,
//     "unique": true,
//     "skills": ["Switch sides", "Ill advisor"],
//     "description": "Gríma Wormtongue was the chief advisor to King Théoden of Rohan. He was the son of Gálmód.",
//     "token_path": "assets/heroes_tokens/grima.png",
//     "token_init_path": "assets/heroes_tokens_init/grima.png",
//     "miniature_path": "assets/heroes_miniatures/grima.png",
//     "battlefield_path": "assets/heroes_battlefield/grima.png"},
//   "Witch-King": {
//     "speed": 7,
//     "initiative": 8,
//     "life_points": 17,
//     "magic_points": 10,
//     "armor": 6,
//     "range": 0,
//     "size": "M",
//     "agility": 6,
//     "stamina": 7,
//     "strength": 7,
//     "magic": 10,
//     "mental": 10,
//     "attack": 7,
//     "ranged_attack": 0,
//     "attack_armor": 2,
//     "cost": 130,
//     "unique": true,
//     "skills": ["Master of the Nine", "Hideous flail"],
//     "description": "The Witch-king of Angmar was the chief of the Nazgûl, King of Angmar and Sauron’s great captain in his wars.",
//     "token_path": "assets/heroes_tokens/witch_king.png",
//     "token_init_path": "assets/heroes_tokens_init/witch_king.png",
//     "miniature_path": "assets/heroes_miniatures/witch_king.png",
//     "battlefield_path": "assets/heroes_battlefield/witch_king.png"},
//   "Moria Orc": {
//     "speed": 6,
//     "initiative": 6,
//     "life_points": 4,
//     "magic_points": 0,
//     "armor": 3,
//     "range": 6,
//     "size": "P",
//     "agility": 6,
//     "stamina": 4,
//     "strength": 3,
//     "magic": 0,
//     "mental": 4,
//     "attack": 4,
//     "ranged_attack": 4,
//     "attack_armor": 1,
//     "cost": 30,
//     "unique": false,
//     "skills": ["Moria blade", "Moria bow"],
//     "description": "Moria Orcs were similar to other Orcs of the Misty Mountains.",
//     "token_path": "assets/heroes_tokens/moria_orc.png",
//     "token_init_path": "assets/heroes_tokens_init/moria_orc.png",
//     "miniature_path": "assets/heroes_miniatures/moria_orc.png",
//     "battlefield_path": "assets/heroes_battlefield/moria_orc.png"},
//   "Uruk-Hai": {
//     "speed": 7,
//     "initiative": 6,
//     "life_points": 7,
//     "magic_points": 0,
//     "armor": 7,
//     "range": 0,
//     "size": "M",
//     "agility": 6,
//     "stamina": 7,
//     "strength": 6,
//     "magic": 0,
//     "mental": 4,
//     "attack": 6,
//     "ranged_attack": 0,
//     "attack_armor": 1,
//     "cost": 65,
//     "unique": false,
//     "skills": ["Isengard blade", "Isengard armor"],
//     "description": "The Uruk-hai were a new breed of Orcs that appeared during the Third Age.",
//     "token_path": "assets/heroes_tokens/uruk_hai.png",
//     "token_init_path": "assets/heroes_tokens_init/uruk_hai.png",
//     "miniature_path": "assets/heroes_miniatures/uruk_hai.png",
//     "battlefield_path": "assets/heroes_battlefield/uruk_hai.png"},
//   "Easterling": {
//     "speed": 5,
//     "initiative": 5,
//     "life_points": 7,
//     "magic_points": 0,
//     "armor": 5,
//     "range": 0,
//     "size": "M",
//     "agility": 5,
//     "stamina": 5,
//     "strength": 5,
//     "magic": 0,
//     "mental": 4,
//     "attack": 6,
//     "ranged_attack": 0,
//     "attack_armor": 1,
//     "cost": 35,
//     "unique": false,
//     "skills": ["Rhûn halberd", "Rhûn armor"],
//     "description": "Easterlings were a race of Men who lived in the vast and uncharted lands of Rhûn, east of Mordor and the Sea of Rhûn.",
//     "token_path": "assets/heroes_tokens/easterling.png",
//     "token_init_path": "assets/heroes_tokens_init/easterling.png",
//     "miniature_path": "assets/heroes_miniatures/easterling.png",
//     "battlefield_path": "assets/heroes_battlefield/easterling.png"},
//   "Corsair of Umbar": {
//     "speed": 6,
//     "initiative": 5,
//     "life_points": 4,
//     "magic_points": 0,
//     "armor": 4,
//     "range": 7,
//     "size": "M",
//     "agility": 6,
//     "stamina": 5,
//     "strength": 4,
//     "magic": 0,
//     "mental": 3,
//     "attack": 6,
//     "ranged_attack": 5,
//     "attack_armor": 1,
//     "cost": 40,
//     "unique": false,
//     "skills": ["Pirate bow", "Pirate daggers"],
//     "description": "The Corsairs of Umbar were sea-raiders and pirates of the Haven of Umbar.",
//     "token_path": "assets/heroes_tokens/corsair_of_umbar.png",
//     "token_init_path": "assets/heroes_tokens_init/corsair_of_umbar.png",
//     "miniature_path": "assets/heroes_miniatures/corsair_of_umbar.png",
//     "battlefield_path": "assets/heroes_battlefield/corsair_of_umbar.png"},
//   "Haradrim Warrior": {
//     "speed": 6,
//     "initiative": 4,
//     "life_points": 6,
//     "magic_points": 0,
//     "armor": 5,
//     "range": 6,
//     "size": "M",
//     "agility": 5,
//     "stamina": 6,
//     "strength": 6,
//     "magic": 0,
//     "mental": 5,
//     "attack": 5,
//     "ranged_attack": 5,
//     "attack_armor": 1,
//     "cost": 35,
//     "unique": false,
//     "skills": ["Harad bow", "Mumakil teamer"],
//     "description": "The Haradrim or the Southrons were the proud and warlike people of the Harad, in the south of Middle-earth.",
//     "token_path": "assets/heroes_tokens/haradrim_warrior.png",
//     "token_init_path": "assets/heroes_tokens_init/haradrim_warrior.png",
//     "miniature_path": "assets/heroes_miniatures/haradrim_warrior.png",
//     "battlefield_path": "assets/heroes_battlefield/haradrim_warrior.png"}
// }
