// Load heroes

export const LOAD_HEROES_START = "LOAD_HEROES_START";
export type LOAD_HEROES_START = typeof LOAD_HEROES_START

export const LOAD_HEROES_SUCCESS = "LOAD_HEROES_SUCCESS";
export type LOAD_HEROES_SUCCESS = typeof LOAD_HEROES_SUCCESS

export const LOAD_HEROES_FAIL = "LOAD_HEROES_FAIL";
export type LOAD_HEROES_FAIL = typeof LOAD_HEROES_FAIL

// Tiles Loading

export const LOAD_TILES_START = "LOAD_TILES_START";
export type LOAD_TILES_START = typeof LOAD_TILES_START

export const LOAD_TILES_SUCCESS = "LOAD_TILES_SUCCESS";
export type LOAD_TILES_SUCCESS = typeof LOAD_TILES_SUCCESS

export const LOAD_TILES_FAIL = "LOAD_TILES_FAIL";
export type LOAD_TILES_FAIL = typeof LOAD_TILES_FAIL

// Tiles Reseting

export const RESET_TILES = "RESET_TILES";
export type RESET_TILES = typeof RESET_TILES

// Tiles Updating

export const UPDATE_TILES = "UPDATE_TILES";
export type UPDATE_TILES = typeof UPDATE_TILES

// Load all heroes

export const LOAD_ALL_HEROES_START = "LOAD_ALL_HEROES_START";
export type LOAD_ALL_HEROES_START = typeof LOAD_ALL_HEROES_START

export const LOAD_ALL_HEROES_SUCCESS = "LOAD_ALL_HEROES_SUCCESS";
export type LOAD_ALL_HEROES_SUCCESS = typeof LOAD_ALL_HEROES_SUCCESS

export const LOAD_ALL_HEROES_FAIL = "LOAD_ALL_HEROES_FAIL";
export type LOAD_ALL_HEROES_FAIL = typeof LOAD_ALL_HEROES_FAIL

// Load all cards

export const LOAD_ALL_CARDS_START = "LOAD_ALL_CARDS_START";
export type LOAD_ALL_CARDS_START = typeof LOAD_ALL_CARDS_START

export const LOAD_ALL_CARDS_SUCCESS = "LOAD_ALL_CARDS_SUCCESS";
export type LOAD_ALL_CARDS_SUCCESS = typeof LOAD_ALL_CARDS_SUCCESS

export const LOAD_ALL_CARDS_FAIL = "LOAD_ALL_CARDS_FAIL";
export type LOAD_ALL_CARDS_FAIL = typeof LOAD_ALL_CARDS_FAIL

// Load players

export const LOAD_PLAYERS_START = "LOAD_PLAYERS_START";
export type LOAD_PLAYERS_START = typeof LOAD_PLAYERS_START

export const LOAD_PLAYERS_SUCCESS = "LOAD_PLAYERS_SUCCESS";
export type LOAD_PLAYERS_SUCCESS = typeof LOAD_PLAYERS_SUCCESS

export const LOAD_PLAYERS_FAIL = "LOAD_PLAYERS_FAIL";
export type LOAD_PLAYERS_FAIL = typeof LOAD_PLAYERS_FAIL

// Update players

export const SET_HERO_SELECTED = "SET_HERO_SELECTED";
export type SET_HERO_SELECTED = typeof SET_HERO_SELECTED

export const SET_HERO_NEW_POSITION = "SET_HERO_NEW_POSITION";
export type SET_HERO_NEW_POSITION = typeof SET_HERO_NEW_POSITION

export const UPDATE_HEROES_STATE = "UPDATE_HEROES_STATE";
export type UPDATE_HEROES_STATE = typeof UPDATE_HEROES_STATE

export const RESET_HEROES_STATE = "RESET_HEROES_STATE";
export type RESET_HEROES_STATE = typeof RESET_HEROES_STATE

// Set heroes order

export const SET_HEROES_ORDER = "SET_HEROES_ORDER";
export type SET_HEROES_ORDER = typeof SET_HEROES_ORDER

export const SET_NEXT_CURRENT_HERO = "SET_NEXT_CURRENT_HERO";
export type SET_NEXT_CURRENT_HERO = typeof SET_NEXT_CURRENT_HERO

// Heroes action points

export const INCREMENT_ACTION_POINTS = "INCREMENT_ACTION_POINTS";
export type INCREMENT_ACTION_POINTS = typeof INCREMENT_ACTION_POINTS

export const DECREMENT_ACTION_POINTS = "DECREMENT_ACTION_POINTS";
export type DECREMENT_ACTION_POINTS = typeof DECREMENT_ACTION_POINTS

export const RESET_ACTION_POINTS = "RESET_ACTION_POINTS";
export type RESET_ACTION_POINTS = typeof RESET_ACTION_POINTS

// Set and update cards Battlefield

export const INITIALIZE_DECK_HAND = "INITIALIZE_DECK_HAND";
export type INITIALIZE_DECK_HAND = typeof INITIALIZE_DECK_HAND

export const DRAW_CARD = "DRAW_CARD";
export type DRAW_CARD = typeof DRAW_CARD

export const PLAY_CARD = "PLAY_CARD";
export type PLAY_CARD = typeof PLAY_CARD
