// Load heroes

export const LOAD_HEROES_START = 'LOAD_HEROES_START'
export type LOAD_HEROES_START = typeof LOAD_HEROES_START

export const LOAD_HEROES_SUCCESS = 'LOAD_HEROES_SUCCESS'
export type LOAD_HEROES_SUCCESS = typeof LOAD_HEROES_SUCCESS

export const LOAD_HEROES_FAIL = 'LOAD_HEROES_FAIL'
export type LOAD_HEROES_FAIL = typeof LOAD_HEROES_FAIL

// Tiles Loading

export const LOAD_TILES_START = 'LOAD_TILES_START'
export type LOAD_TILES_START = typeof LOAD_TILES_START

export const LOAD_TILES_SUCCESS = 'LOAD_TILES_SUCCESS'
export type LOAD_TILES_SUCCESS = typeof LOAD_TILES_SUCCESS

export const LOAD_TILES_FAIL = 'LOAD_TILES_FAIL'
export type LOAD_TILES_FAIL = typeof LOAD_TILES_FAIL

// Tiles Updating

export const UPDATE_TILES = 'UPDATE_TILES'
export type UPDATE_TILES = typeof UPDATE_TILES

// Load all heroes

export const LOAD_ALL_HEROES_START = 'LOAD_ALL_HEROES_START'
export type LOAD_ALL_HEROES_START = typeof LOAD_ALL_HEROES_START

export const LOAD_ALL_HEROES_SUCCESS = 'LOAD_ALL_HEROES_SUCCESS'
export type LOAD_ALL_HEROES_SUCCESS = typeof LOAD_ALL_HEROES_SUCCESS

export const LOAD_ALL_HEROES_FAIL = 'LOAD_ALL_HEROES_FAIL'
export type LOAD_ALL_HEROES_FAIL = typeof LOAD_ALL_HEROES_FAIL

// Load all cards

export const LOAD_ALL_CARDS_START = 'LOAD_ALL_CARDS_START'
export type LOAD_ALL_CARDS_START = typeof LOAD_ALL_CARDS_START

export const LOAD_ALL_CARDS_SUCCESS = 'LOAD_ALL_CARDS_SUCCESS'
export type LOAD_ALL_CARDS_SUCCESS = typeof LOAD_ALL_CARDS_SUCCESS

export const LOAD_ALL_CARDS_FAIL = 'LOAD_ALL_CARDS_FAIL'
export type LOAD_ALL_CARDS_FAIL = typeof LOAD_ALL_CARDS_FAIL

// Load players

export const LOAD_PLAYERS_START = 'LOAD_PLAYERS_START'
export type LOAD_PLAYERS_START = typeof LOAD_PLAYERS_START

export const LOAD_PLAYERS_SUCCESS = 'LOAD_PLAYERS_SUCCESS'
export type LOAD_PLAYERS_SUCCESS = typeof LOAD_PLAYERS_SUCCESS

export const LOAD_PLAYERS_FAIL = 'LOAD_PLAYERS_FAIL'
export type LOAD_PLAYERS_FAIL = typeof LOAD_PLAYERS_FAIL
